// Curated vocab and tukh data for the Games hub. Mirrors the Swift sources
// in FirstLetterMatchView, BaniIdentifierView, TukhCompletionView,
// UcharanCatchView, and MemoryMatchView.

export type WordEntry = {
  word: string;
  firstLetter: string;
  english: string;
};

export const wordBank: WordEntry[] = [
  { word: "ਉਪਦੇਸ", firstLetter: "ੳ", english: "Teaching" },
  { word: "ਉਧਰ", firstLetter: "ੳ", english: "Save" },
  { word: "ਅੰਮ੍ਰਿਤ", firstLetter: "ਅ", english: "Nectar" },
  { word: "ਅਕਾਲ", firstLetter: "ਅ", english: "Timeless" },
  { word: "ਅਨਹਦ", firstLetter: "ਅ", english: "Unstruck" },
  { word: "ਅੰਤ", firstLetter: "ਅ", english: "End" },
  { word: "ਆਦਿ", firstLetter: "ਅ", english: "Beginning" },
  { word: "ਆਨੰਦ", firstLetter: "ਅ", english: "Bliss" },
  { word: "ਅਖੰਡ", firstLetter: "ਅ", english: "Unbroken" },
  { word: "ਇਕ", firstLetter: "ੲ", english: "One" },
  { word: "ਇਛਾ", firstLetter: "ੲ", english: "Desire" },
  { word: "ਸਤਿਗੁਰੁ", firstLetter: "ਸ", english: "True Guru" },
  { word: "ਸਾਚਾ", firstLetter: "ਸ", english: "True" },
  { word: "ਸਾਧ", firstLetter: "ਸ", english: "Saint" },
  { word: "ਸੰਤ", firstLetter: "ਸ", english: "Saint" },
  { word: "ਸਚੁ", firstLetter: "ਸ", english: "Truth" },
  { word: "ਸਬਦ", firstLetter: "ਸ", english: "Word" },
  { word: "ਸੇਵਾ", firstLetter: "ਸ", english: "Service" },
  { word: "ਸਿਮਰਨ", firstLetter: "ਸ", english: "Remembrance" },
  { word: "ਸੁਖ", firstLetter: "ਸ", english: "Comfort" },
  { word: "ਸਾਹਿਬੁ", firstLetter: "ਸ", english: "Master" },
  { word: "ਸੰਗਤਿ", firstLetter: "ਸ", english: "Congregation" },
  { word: "ਹਰਿ", firstLetter: "ਹ", english: "Lord" },
  { word: "ਹਉਮੈ", firstLetter: "ਹ", english: "Ego" },
  { word: "ਹੁਕਮੁ", firstLetter: "ਹ", english: "Command" },
  { word: "ਹਿਰਦਾ", firstLetter: "ਹ", english: "Heart" },
  { word: "ਕਰਤਾ", firstLetter: "ਕ", english: "Creator" },
  { word: "ਕਿਰਪਾ", firstLetter: "ਕ", english: "Mercy" },
  { word: "ਕਰਮ", firstLetter: "ਕ", english: "Deed" },
  { word: "ਕਾਮ", firstLetter: "ਕ", english: "Lust" },
  { word: "ਕ੍ਰੋਧ", firstLetter: "ਕ", english: "Anger" },
  { word: "ਕਲਿ", firstLetter: "ਕ", english: "Dark age" },
  { word: "ਖਾਲਸਾ", firstLetter: "ਖ", english: "Pure" },
  { word: "ਖੰਡ", firstLetter: "ਖ", english: "Realm" },
  { word: "ਖਸਮੁ", firstLetter: "ਖ", english: "Master" },
  { word: "ਗੁਰੂ", firstLetter: "ਗ", english: "Guru" },
  { word: "ਗੁਰੁ", firstLetter: "ਗ", english: "Guru" },
  { word: "ਗਿਆਨ", firstLetter: "ਗ", english: "Wisdom" },
  { word: "ਗੁਣ", firstLetter: "ਗ", english: "Virtue" },
  { word: "ਗਤਿ", firstLetter: "ਗ", english: "Liberation" },
  { word: "ਗੁਰਮੁਖਿ", firstLetter: "ਗ", english: "Guru-oriented" },
  { word: "ਘਰੁ", firstLetter: "ਘ", english: "Home" },
  { word: "ਚਰਨ", firstLetter: "ਚ", english: "Feet" },
  { word: "ਚਾਉ", firstLetter: "ਚ", english: "Joy" },
  { word: "ਚੰਦ", firstLetter: "ਚ", english: "Moon" },
  { word: "ਛਡਿ", firstLetter: "ਛ", english: "Leave" },
  { word: "ਜਨ", firstLetter: "ਜ", english: "Servant" },
  { word: "ਜੋਤਿ", firstLetter: "ਜ", english: "Light" },
  { word: "ਜਪੁ", firstLetter: "ਜ", english: "Meditate" },
  { word: "ਜੁਗ", firstLetter: "ਜ", english: "Age" },
  { word: "ਜਗਤ", firstLetter: "ਜ", english: "World" },
  { word: "ਜੀਉ", firstLetter: "ਜ", english: "Life" },
  { word: "ਟਿਕੈ", firstLetter: "ਟ", english: "Settles" },
  { word: "ਡਰੁ", firstLetter: "ਡ", english: "Fear" },
  { word: "ਤੂੰ", firstLetter: "ਤ", english: "You" },
  { word: "ਤਾਪੁ", firstLetter: "ਤ", english: "Heat" },
  { word: "ਤ੍ਰਿਪਤਿ", firstLetter: "ਤ", english: "Satisfaction" },
  { word: "ਥਲ", firstLetter: "ਥ", english: "Land" },
  { word: "ਦਾਸ", firstLetter: "ਦ", english: "Slave" },
  { word: "ਦਇਆ", firstLetter: "ਦ", english: "Compassion" },
  { word: "ਦਾਨੁ", firstLetter: "ਦ", english: "Charity" },
  { word: "ਦਰਸ", firstLetter: "ਦ", english: "Vision" },
  { word: "ਦੁਖ", firstLetter: "ਦ", english: "Sorrow" },
  { word: "ਧਨੁ", firstLetter: "ਧ", english: "Wealth" },
  { word: "ਧੀਰਜ", firstLetter: "ਧ", english: "Patience" },
  { word: "ਧਰਤਿ", firstLetter: "ਧ", english: "Earth" },
  { word: "ਧਰਮ", firstLetter: "ਧ", english: "Righteousness" },
  { word: "ਨਾਮ", firstLetter: "ਨ", english: "Name" },
  { word: "ਨਾਨਕ", firstLetter: "ਨ", english: "Nanak" },
  { word: "ਨਿਰੰਕਾਰ", firstLetter: "ਨ", english: "Formless" },
  { word: "ਨਿਰਭਉ", firstLetter: "ਨ", english: "Fearless" },
  { word: "ਨਿਰਵੈਰੁ", firstLetter: "ਨ", english: "Without enmity" },
  { word: "ਨੈਨ", firstLetter: "ਨ", english: "Eyes" },
  { word: "ਪ੍ਰਭੁ", firstLetter: "ਪ", english: "Lord" },
  { word: "ਪਿਤਾ", firstLetter: "ਪ", english: "Father" },
  { word: "ਪਾਣੀ", firstLetter: "ਪ", english: "Water" },
  { word: "ਪਿਆਰ", firstLetter: "ਪ", english: "Love" },
  { word: "ਪੁਨਿ", firstLetter: "ਪ", english: "Virtue" },
  { word: "ਪਉਣ", firstLetter: "ਪ", english: "Air" },
  { word: "ਫਲ", firstLetter: "ਫ", english: "Fruit" },
  { word: "ਫੁਲ", firstLetter: "ਫ", english: "Flower" },
  { word: "ਬਾਣੀ", firstLetter: "ਬ", english: "Bani" },
  { word: "ਬਾਬਾ", firstLetter: "ਬ", english: "Elder" },
  { word: "ਬੀਜ", firstLetter: "ਬ", english: "Seed" },
  { word: "ਭਗਤ", firstLetter: "ਭ", english: "Devotee" },
  { word: "ਭਾਉ", firstLetter: "ਭ", english: "Love" },
  { word: "ਭੁਖ", firstLetter: "ਭ", english: "Hunger" },
  { word: "ਮਨ", firstLetter: "ਮ", english: "Mind" },
  { word: "ਮਾਤਾ", firstLetter: "ਮ", english: "Mother" },
  { word: "ਮੁਖ", firstLetter: "ਮ", english: "Face" },
  { word: "ਮੁਕਤਿ", firstLetter: "ਮ", english: "Liberation" },
  { word: "ਮੋਹ", firstLetter: "ਮ", english: "Attachment" },
  { word: "ਮਾਇਆ", firstLetter: "ਮ", english: "Illusion" },
  { word: "ਮਿਤੁ", firstLetter: "ਮ", english: "Friend" },
  { word: "ਯਾਦ", firstLetter: "ਯ", english: "Memory" },
  { word: "ਰਾਮ", firstLetter: "ਰ", english: "Lord" },
  { word: "ਰੰਗ", firstLetter: "ਰ", english: "Colour" },
  { word: "ਰਾਜ", firstLetter: "ਰ", english: "Kingdom" },
  { word: "ਰਸ", firstLetter: "ਰ", english: "Nectar" },
  { word: "ਰੀਤਿ", firstLetter: "ਰ", english: "Way" },
  { word: "ਲੋਕ", firstLetter: "ਲ", english: "World" },
  { word: "ਲਾਜ", firstLetter: "ਲ", english: "Shame" },
  { word: "ਲਾਲ", firstLetter: "ਲ", english: "Beloved" },
  { word: "ਵਾਹਿਗੁਰੂ", firstLetter: "ਵ", english: "Waheguru" },
  { word: "ਵਾਰ", firstLetter: "ਵ", english: "Vaar" },
  { word: "ਵਡਾ", firstLetter: "ਵ", english: "Great" },
  { word: "ੜਾੜਾ", firstLetter: "ੜ", english: "Rarra letter" },
];

export type BaniItem = { tukh: string; bani: string };

export const baniBank: BaniItem[] = [
  { tukh: "ਆਦਿ ਸਚੁ; ਜੁਗਾਦਿ ਸਚੁ॥", bani: "Japji Sahib" },
  { tukh: "ਹੈ ਭੀ ਸਚੁ; ਨਾਨਕ ਹੋਸੀ ਭੀ ਸਚੁ॥੧॥", bani: "Japji Sahib" },
  { tukh: "ਸੋਚੈ. ਸੋਚਿ ਨ ਹੋਵਈ; ਜੇ ਸੋਚੀ ਲਖ ਵਾਰ॥", bani: "Japji Sahib" },
  { tukh: "ਚੁਪੈ. ਚੁਪਿ ਨ ਹੋਵਈ; ਜੇ ਲਾਇ ਰਹਾ ਲਿਵਤਾਰ॥", bani: "Japji Sahib" },
  { tukh: "ਭੁਖਿਆ. ਭੁਖ ਨ ਉਤਰੀ; ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ॥", bani: "Japji Sahib" },
  { tukh: "ਸਹਸ ਸਿਆਣਪਾ ਲਖ ਹੋਹਿ; ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ॥", bani: "Japji Sahib" },
  { tukh: "ਕਿਵ. ਸਚਿਆਰਾ ਹੋਈਐ; ਕਿਵ. ਕੂੜੈ ਤੁਟੈ ਪਾਲਿ॥", bani: "Japji Sahib" },
  { tukh: "ਹੁਕਮਿ ਰਜਾਈ ਚਲਣਾ; ਨਾਨਕ ਲਿਖਿਆ ਨਾਲਿ॥੧॥", bani: "Japji Sahib" },
  { tukh: "ਹੁਕਮੀ ਹੋਵਨਿ ਆਕਾਰ; ਹੁਕਮੁ. ਨ ਕਹਿਆ ਜਾਈ॥", bani: "Japji Sahib" },
  { tukh: "ਹੁਕਮੀ ਹੋਵਨਿ ਜੀਅ; ਹੁਕਮਿ ਮਿਲੈ ਵਡਿਆਈ॥", bani: "Japji Sahib" },
  { tukh: "ਹੁਕਮੀ ਉਤਮੁ ਨੀਚੁ; ਹੁਕਮਿ ਲਿਖਿ ਦੁਖ ਸੁਖ ਪਾਈਅਹਿ॥", bani: "Japji Sahib" },
  { tukh: "ਇਕਨਾ ਹੁਕਮੀ ਬਖਸੀਸ; ਇਕਿ ਹੁਕਮੀ ਸਦਾ ਭਵਾਈਅਹਿ॥", bani: "Japji Sahib" },
  { tukh: "ਹੁਕਮੈ ਅੰਦਰਿ ਸਭੁ ਕੋ; ਬਾਹਰਿ ਹੁਕਮ ਨ ਕੋਇ॥", bani: "Japji Sahib" },
  { tukh: "ਨਾਨਕ ਹੁਕਮੈ ਜੇ ਬੁਝੈ; ਤ ਹਉਮੈ ਕਹੈ ਨ ਕੋਇ॥੨॥", bani: "Japji Sahib" },
  { tukh: "ਗਾਵੈ ਕੋ ਤਾਣੁ; ਹੋਵੈ ਕਿਸੈ ਤਾਣੁ॥", bani: "Japji Sahib" },
  { tukh: "ਗਾਵੈ ਕੋ ਦਾਤਿ; ਜਾਣੈ ਨੀਸਾਣੁ॥", bani: "Japji Sahib" },
  { tukh: "ਗਾਵੈ ਕੋ; ਗੁਣ ਵਡਿਆਈਆ ਚਾਰ॥", bani: "Japji Sahib" },
  { tukh: "ਗਾਵੈ ਕੋ; ਵਿਦਿਆ ਵਿਖਮੁ ਵੀਚਾਰੁ॥", bani: "Japji Sahib" },
  { tukh: "ਚੱਕ੍ਰ ਚਿਹਨ ਅਰੁ ਬਰਨ ਜਾਤਿ; ਅਰੁ ਪਾਤਿ ਨਹਿਨ ਜਿਹ॥", bani: "Jaap Sahib" },
  { tukh: "ਰੂਪ ਰੰਗ ਅਰੁ ਰੇਖ ਭੇਖ; ਕੋਊ ਕਹਿ ਨ ਸਕਤਿ ਕਿਹ॥", bani: "Jaap Sahib" },
  { tukh: "ਅਚਲ ਮੂਰਤਿ ਅਨਭਉ ਪ੍ਰਕਾਸ; ਅਮਿਤੋਜ ਕਹਿੱਜੈ॥", bani: "Jaap Sahib" },
  { tukh: "ਕੋਟਿ ਇੰਦ੍ਰ ਇੰਦ੍ਰਾਣਿ; ਸਾਹਿ ਸਾਹਾਣਿ ਗਣਿੱਜੈ॥", bani: "Jaap Sahib" },
  { tukh: "ਤ੍ਰਿਭਵਣ ਮਹੀਪ ਸੁਰ ਨਰ ਅਸੁਰ; ਨੇਤ ਨੇਤ ਬਨ ਤ੍ਰਿਣ ਕਹਤ॥", bani: "Jaap Sahib" },
  { tukh: "ਤ੍ਵ ਸਰਬ ਨਾਮ. ਕਥੈ ਕਵਨ; ਕਰਮ ਨਾਮ ਬਰਨਤ ਸੁਮਤਿ॥੧॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਚੰਦ੍ਰ ਚੰਦ੍ਰੇ॥ਨਮੋ ਭਾਨ ਭਾਨੇ॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਗੀਤ ਗੀਤੇ; ਨਮੋ ਤਾਨ ਤਾਨੇ॥੪੭॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਨਿਰਤ ਨਿਰਤੇ; ਨਮੋ ਨਾਦ ਨਾਦੇ॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਪਾਨ ਪਾਨੇ; ਨਮੋ ਬਾਦ ਬਾਦੇ॥੪੮॥", bani: "Jaap Sahib" },
  { tukh: "ਅਨੰਗੀ ਅਨਾਮੇ; ਸਮਸਤੀ ਸਰੂਪੇ॥", bani: "Jaap Sahib" },
  { tukh: "ਪ੍ਰਭੰਗੀ ਪ੍ਰਮਾਥੇ; ਸਮਸਤੀ ਬਿਭੂਤੇ॥੪੯॥", bani: "Jaap Sahib" },
  { tukh: "ਕਲੰਕੰ ਬਿਨਾ; ਨੇਕਲੰਕੀ ਸਰੂਪੇ॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਰਾਜ ਰਾਜੇਸ੍ਵਰੰ; ਪਰਮ ਰੂਪੇ॥੫੦॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਜੋਗ ਜੋਗੇਸ੍ਵਰੰ; ਪਰਮ ਸਿੱਧੇ॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਰਾਜ ਰਾਜੇਸ੍ਵਰੰ; ਪਰਮ ਬ੍ਰਿੱਧੇ॥੫੧॥", bani: "Jaap Sahib" },
  { tukh: "ਅਭੇਖੀ ਅਭਰਮੀ ਅਭੋਗੀ ਅਭੁਗਤੇ॥", bani: "Jaap Sahib" },
  { tukh: "ਨਮੋ ਜੋਗ ਜੋਗੇਸ੍ਵਰੰ; ਪਰਮ ਜੁਗਤੇ॥੫੩॥", bani: "Jaap Sahib" },
  { tukh: "ਸ੍ਰੀ ਗੁਰਦੇਵ ਏ; ਨਮਹ॥੧॥", bani: "Sukhmani Sahib" },
  { tukh: "ਸਿਮਰਉ. ਸਿਮਰਿ ਸਿਮਰਿ; ਸੁਖੁ ਪਾਵਉ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਕਲਿ ਕਲੇਸ; ਤਨ ਮਾਹਿ ਮਿਟਾਵਉ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਸਿਮਰਉ ਜਾਸੁ; ਬਿਸੁੰਭਰ ਏਕੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਨਾਮੁ ਜਪਤ; ਅਗਨਤ ਅਨੇਕੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਬੇਦ ਪੁਰਾਨ; ਸਿੰਮ੍ਰਿਤਿ ਸੁਧਾਖੵਰ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਕੀਨੇ ਰਾਮ ਨਾਮ; ਇਕ ਆਖੵਰ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਕਿਨਕਾ ਏਕ; ਜਿਸੁ ਜੀਅ ਬਸਾਵੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਤਾ ਕੀ ਮਹਿਮਾ; ਗਨੀ ਨ ਆਵੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਕਾਂਖੀ; ਏਕੈ ਦਰਸ ਤੁਹਾਰੋ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਨਾਨਕ. ਉਨ ਸੰਗਿ; ਮੋਹਿ ਉਧਾਰੋ॥੧॥", bani: "Sukhmani Sahib" },
  { tukh: "ਸੁਖਮਨੀ ਸੁਖ; ਅੰਮ੍ਰਿਤ ਪ੍ਰਭ ਨਾਮੁ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਭਗਤ ਜਨਾ ਕੈ; ਮਨਿ ਬਿਸ੍ਰਾਮ॥ਰਹਾਉ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਪ੍ਰਭ ਕੈ ਸਿਮਰਨਿ; ਗਰਭਿ ਨ ਬਸੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਪ੍ਰਭ ਕੈ ਸਿਮਰਨਿ; ਦੂਖੁ ਜਮੁ ਨਸੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਪ੍ਰਭ ਕੈ ਸਿਮਰਨਿ; ਕਾਲੁ ਪਰਹਰੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਪ੍ਰਭ ਕੈ ਸਿਮਰਨਿ; ਦੁਸਮਨੁ ਟਰੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਪ੍ਰਭ ਸਿਮਰਤ; ਕਛੁ ਬਿਘਨੁ ਨ ਲਾਗੈ॥", bani: "Sukhmani Sahib" },
  { tukh: "ਸਤਿਗੁਰੁ. ਤ ਪਾਇਆ ਸਹਜ ਸੇਤੀ; ਮਨਿ ਵਜੀਆ ਵਾਧਾਈਆ॥", bani: "Anand Sahib" },
  { tukh: "ਸਬਦੋ ਤ ਗਾਵਹੁ ਹਰੀ ਕੇਰਾ; ਮਨਿ ਜਿਨੀ ਵਸਾਇਆ॥", bani: "Anand Sahib" },
  { tukh: "ਕਹੈ ਨਾਨਕੁ. ਅਨੰਦੁ ਹੋਆ; ਸਤਿਗੁਰੂ. ਮੈ ਪਾਇਆ॥੧॥", bani: "Anand Sahib" },
  { tukh: "ਏ ਮਨ ਮੇਰਿਆ; ਤੂ ਸਦਾ ਰਹੁ ਹਰਿ ਨਾਲੇ॥", bani: "Anand Sahib" },
  { tukh: "ਹਰਿ ਨਾਲਿ ਰਹੁ ਤੂ ਮੰਨ ਮੇਰੇ; ਦੂਖ ਸਭਿ ਵਿਸਾਰਣਾ॥", bani: "Anand Sahib" },
  { tukh: "ਅੰਗੀਕਾਰੁ ਓਹੁ ਕਰੇ ਤੇਰਾ; ਕਾਰਜ ਸਭਿ ਸਵਾਰਣਾ॥", bani: "Anand Sahib" },
  { tukh: "ਸਭਨਾ ਗਲਾ ਸਮਰਥੁ ਸੁਆਮੀ; ਸੋ. ਕਿਉ ਮਨਹੁ ਵਿਸਾਰੇ॥", bani: "Anand Sahib" },
  { tukh: "ਕਹੈ ਨਾਨਕੁ. ਮੰਨ ਮੇਰੇ; ਸਦਾ ਰਹੁ ਹਰਿ ਨਾਲੇ॥੨॥", bani: "Anand Sahib" },
  { tukh: "ਸਾਚੇ ਸਾਹਿਬਾ; ਕਿਆ ਨਾਹੀ. ਘਰਿ ਤੇਰੈ॥", bani: "Anand Sahib" },
  { tukh: "ਘਰਿ ਤ ਤੇਰੈ. ਸਭੁ ਕਿਛੁ ਹੈ; ਜਿਸੁ ਦੇਹਿ ਸੁ ਪਾਵਏ॥", bani: "Anand Sahib" },
  { tukh: "ਸਦਾ ਸਿਫਤਿ ਸਲਾਹ ਤੇਰੀ; ਨਾਮੁ ਮਨਿ ਵਸਾਵਏ॥", bani: "Anand Sahib" },
  { tukh: "ਨਾਮੁ ਜਿਨ ਕੈ ਮਨਿ ਵਸਿਆ; ਵਾਜੇ ਸਬਦ ਘਨੇਰੇ॥", bani: "Anand Sahib" },
  { tukh: "ਕਹੈ ਨਾਨਕੁ. ਸਚੇ ਸਾਹਿਬ; ਕਿਆ ਨਾਹੀ. ਘਰਿ ਤੇਰੈ॥੩॥", bani: "Anand Sahib" },
  { tukh: "ਸਾਚਾ ਨਾਮੁ; ਮੇਰਾ ਆਧਾਰੋ॥", bani: "Anand Sahib" },
  { tukh: "ਸਾਚੁ ਨਾਮੁ ਅਧਾਰੁ ਮੇਰਾ; ਜਿਨਿ ਭੁਖਾ ਸਭਿ ਗਵਾਈਆ॥", bani: "Anand Sahib" },
  { tukh: "ਕਰਿ ਸਾਂਤਿ ਸੁਖ ਮਨਿ ਆਇ ਵਸਿਆ; ਜਿਨਿ ਇਛਾ ਸਭਿ ਪੁਜਾਈਆ॥", bani: "Anand Sahib" },
  { tukh: "ਸਦਾ ਕੁਰਬਾਣੁ ਕੀਤਾ ਗੁਰੂ ਵਿਟਹੁ; ਜਿਸ ਦੀਆ ਏਹਿ ਵਡਿਆਈਆ॥", bani: "Anand Sahib" },
  { tukh: "ਕਹੈ ਨਾਨਕੁ. ਸੁਣਹੁ ਸੰਤਹੁ; ਸਬਦਿ ਧਰਹੁ ਪਿਆਰੋ॥", bani: "Anand Sahib" },
  { tukh: "ਹਰਿ ਜੁਗੁ ਜੁਗੁ. ਭਗਤ ਉਪਾਇਆ; ਪੈਜ ਰਖਦਾ ਆਇਆ. ਰਾਮ ਰਾਜੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਹਰਣਾਖਸੁ ਦੁਸਟੁ ਹਰਿ ਮਾਰਿਆ; ਪ੍ਰਹਲਾਦੁ ਤਰਾਇਆ॥", bani: "Rehras Sahib" },
  { tukh: "ਅਹੰਕਾਰੀਆ ਨਿੰਦਕਾ. ਪਿਠਿ ਦੇਇ; ਨਾਮਦੇਉ. ਮੁਖਿ ਲਾਇਆ॥", bani: "Rehras Sahib" },
  { tukh: "ਜਨ ਨਾਨਕ. ਐਸਾ ਹਰਿ ਸੇਵਿਆ; ਅੰਤਿ ਲਏ ਛਡਾਇਆ॥੪॥੧੩॥੨੦॥", bani: "Rehras Sahib" },
  { tukh: "ਦੁਖੁ ਦਾਰੂ. ਸੁਖੁ ਰੋਗੁ ਭਇਆ; ਜਾ ਸੁਖੁ. ਤਾਮਿ ਨ ਹੋਈ॥", bani: "Rehras Sahib" },
  { tukh: "ਤੂੰ ਕਰਤਾ ਕਰਣਾ, ਮੈ ਨਾਹੀ; ਜਾ ਹਉ ਕਰੀ. ਨ ਹੋਈ॥੧॥", bani: "Rehras Sahib" },
  { tukh: "ਬਲਿਹਾਰੀ ਕੁਦਰਤਿ ਵਸਿਆ॥", bani: "Rehras Sahib" },
  { tukh: "ਤੇਰਾ ਅੰਤੁ. ਨ ਜਾਈ ਲਖਿਆ॥੧॥ਰਹਾਉ॥", bani: "Rehras Sahib" },
  { tukh: "ਜਾਤਿ ਮਹਿ ਜੋਤਿ. ਜੋਤਿ ਮਹਿ ਜਾਤਾ; ਅਕਲ ਕਲਾ ਭਰਪੂਰਿ ਰਹਿਆ॥", bani: "Rehras Sahib" },
  { tukh: "ਤੂੰ ਸਚਾ ਸਾਹਿਬੁ. ਸਿਫਤਿ ਸੁਆਲਿੑਉ; ਜਿਨਿ ਕੀਤੀ. ਸੋ ਪਾਰਿ ਪਇਆ॥", bani: "Rehras Sahib" },
  { tukh: "ਕਹੁ ਨਾਨਕ. ਕਰਤੇ ਕੀਆ ਬਾਤਾ; ਜੋ ਕਿਛੁ ਕਰਣਾ, ਸੁ ਕਰਿ ਰਹਿਆ॥੨॥", bani: "Rehras Sahib" },
  { tukh: "ਸੋਦਰੁ ਰਾਗੁ ਆਸਾ ਮਹਲਾ ੧", bani: "Rehras Sahib" },
  { tukh: "ਸੋ ਦਰੁ ਤੇਰਾ ਕੇਹਾ, ਸੋ ਘਰੁ ਕੇਹਾ; ਜਿਤੁ ਬਹਿ ਸਰਬ ਸਮਾਲੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਵਾਜੇ ਤੇਰੇ ਨਾਦ ਅਨੇਕ ਅਸੰਖਾ; ਕੇਤੇ ਤੇਰੇ ਵਾਵਣਹਾਰੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਕੇਤੇ ਤੇਰੇ ਰਾਗ ਪਰੀ ਸਿਉ ਕਹੀਅਹਿ; ਕੇਤੇ ਤੇਰੇ ਗਾਵਣਹਾਰੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਗਾਵਨਿ ਤੁਧਨੋ ਪਵਣੁ ਪਾਣੀ ਬੈਸੰਤਰੁ; ਗਾਵੈ ਰਾਜਾਧਰਮੁ ਦੁਆਰੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਗਾਵਨਿ ਤੁਧਨੋ ਚਿਤੁ ਗੁਪਤੁ ਲਿਖਿ ਜਾਣਨਿ; ਲਿਖਿ ਲਿਖਿ ਧਰਮੁ ਬੀਚਾਰੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਗਾਵਨਿ ਤੁਧਨੋ ਈਸਰੁ ਬ੍ਰਹਮਾ ਦੇਵੀ; ਸੋਹਨਿ ਤੇਰੇ ਸਦਾ ਸਵਾਰੇ॥", bani: "Rehras Sahib" },
  { tukh: "ਸੋਹਿਲਾ ਰਾਗੁ ਗਉੜੀ ਦੀਪਕੀ ਮਹਲਾ ੧", bani: "Kirtan Sohila" },
  { tukh: "ਜੈ ਘਰਿ ਕੀਰਤਿ ਆਖੀਐ; ਕਰਤੇ ਕਾ ਹੋਇ ਬੀਚਾਰੋ॥", bani: "Kirtan Sohila" },
  { tukh: "ਤਿਤੁ ਘਰਿ ਗਾਵਹੁ ਸੋਹਿਲਾ; ਸਿਵਰਿਹੁ ਸਿਰਜਣਹਾਰੋ॥੧॥", bani: "Kirtan Sohila" },
  { tukh: "ਤੁਮ ਗਾਵਹੁ; ਮੇਰੇ ਨਿਰਭਉ ਕਾ ਸੋਹਿਲਾ॥", bani: "Kirtan Sohila" },
  { tukh: "ਹਉ ਵਾਰੀ; ਜਿਤੁ ਸੋਹਿਲੈ ਸਦਾ ਸੁਖੁ ਹੋਇ॥੧॥ਰਹਾਉ॥", bani: "Kirtan Sohila" },
  { tukh: "ਨਿਤ ਨਿਤ ਜੀਅੜੇ ਸਮਾਲੀਅਨਿ; ਦੇਖੈਗਾ ਦੇਵਣਹਾਰੁ॥", bani: "Kirtan Sohila" },
  { tukh: "ਤੇਰੇ ਦਾਨੈ ਕੀਮਤਿ ਨਾ ਪਵੈ; ਤਿਸੁ ਦਾਤੇ ਕਵਣੁ ਸੁਮਾਰੁ॥੨॥", bani: "Kirtan Sohila" },
  { tukh: "ਸੰਬਤਿ ਸਾਹਾ ਲਿਖਿਆ; ਮਿਲਿ ਕਰਿ ਪਾਵਹੁ ਤੇਲੁ॥", bani: "Kirtan Sohila" },
  { tukh: "ਦੇਹੁ ਸਜਣ ਅਸੀਸੜੀਆ; ਜਿਉ ਹੋਵੈ ਸਾਹਿਬ ਸਿਉ ਮੇਲੁ॥੩॥", bani: "Kirtan Sohila" },
  { tukh: "ਘਰਿ ਘਰਿ ਏਹੁ ਪਾਹੁਚਾ; ਸਦੜੇ ਨਿਤ ਪਵੰਨਿ॥", bani: "Kirtan Sohila" },
  { tukh: "ਸਦਣਹਾਰਾ ਸਿਮਰੀਐ; ਨਾਨਕ. ਸੇ ਦਿਹ ਆਵੰਨਿ॥੪॥੧॥", bani: "Kirtan Sohila" },
  { tukh: "ਛਿਅ ਘਰ, ਛਿਅ ਗੁਰ; ਛਿਅ ਉਪਦੇਸ॥", bani: "Kirtan Sohila" },
  { tukh: "ਗੁਰੁ ਗੁਰੁ ਏਕੋ; ਵੇਸ ਅਨੇਕ॥੧॥", bani: "Kirtan Sohila" },
  { tukh: "ਬਾਬਾ, ਜੈ ਘਰਿ; ਕਰਤੇ ਕੀਰਤਿ ਹੋਇ॥", bani: "Kirtan Sohila" },
  { tukh: "ਸੋ ਘਰੁ ਰਾਖੁ; ਵਡਾਈ ਤੋਇ॥੧॥ਰਹਾਉ॥", bani: "Kirtan Sohila" },
  { tukh: "ਵਿਸੁਏ ਚਸਿਆ ਘੜੀਆ ਪਹਰਾ; ਥਿਤੀ ਵਾਰੀ ਮਾਹੁ ਹੋਆ॥", bani: "Kirtan Sohila" },
  { tukh: "ਸੂਰਜੁ ਏਕੋ; ਰੁਤਿ ਅਨੇਕ॥", bani: "Kirtan Sohila" },
  { tukh: "ਨਾਨਕ; ਕਰਤੇ ਕੇ ਕੇਤੇ ਵੇਸ॥੨॥੨॥", bani: "Kirtan Sohila" },
  { tukh: "ਗੁਰਦੇਵ ਮਾਤਾ. ਗੁਰਦੇਵ ਪਿਤਾ; ਗੁਰਦੇਵ ਸੁਆਮੀ ਪਰਮੇਸੁਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਸਖਾ. ਅਗਿਆਨ ਭੰਜਨੁ; ਗੁਰਦੇਵ ਬੰਧਿਪ ਸਹੋਦਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਦਾਤਾ. ਹਰਿ ਨਾਮੁ ਉਪਦੇਸੈ; ਗੁਰਦੇਵ ਮੰਤੁ. ਨਿਰੋਧਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਸਾਂਤਿ ਸਤਿ ਬੁਧਿ ਮੂਰਤਿ; ਗੁਰਦੇਵ. ਪਾਰਸ ਪਰਸ ਪਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਤੀਰਥੁ ਅੰਮ੍ਰਿਤ ਸਰੋਵਰੁ; ਗੁਰ ਗਿਆਨ ਮਜਨੁ ਅਪਰੰਪਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਕਰਤਾ. ਸਭਿ ਪਾਪ ਹਰਤਾ; ਗੁਰਦੇਵ, ਪਤਿਤ ਪਵਿਤ ਕਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ. ਆਦਿ ਜੁਗਾਦਿ ਜੁਗੁ ਜੁਗੁ; ਗੁਰਦੇਵ ਮੰਤੁ ਹਰਿ ਜਪਿ ਉਧਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਸੰਗਤਿ. ਪ੍ਰਭ ਮੇਲਿ ਕਰਿ ਕਿਰਪਾ; ਹਮ ਮੂੜ ਪਾਪੀ. ਜਿਤੁ ਲਗਿ ਤਰਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਗੁਰਦੇਵ ਸਤਿਗੁਰੁ ਪਾਰਬ੍ਰਹਮੁ ਪਰਮੇਸਰੁ; ਗੁਰਦੇਵ ਨਾਨਕ ਹਰਿ ਨਮਸਕਰਾ॥੧॥", bani: "Bavan Akhri" },
  { tukh: "ਆਪਹਿ ਕੀਆ ਕਰਾਇਆ; ਆਪਹਿ ਕਰਨੈ ਜੋਗੁ॥", bani: "Bavan Akhri" },
  { tukh: "ਨਾਨਕ. ਏਕੋ ਰਵਿ ਰਹਿਆ; ਦੂਸਰ. ਹੋਆ ਨ ਹੋਗੁ॥੧॥", bani: "Bavan Akhri" },
  { tukh: "ਓਅੰ ਸਾਧ ਸਤਿਗੁਰ; ਨਮਸਕਾਰੰ॥", bani: "Bavan Akhri" },
  { tukh: "ਆਦਿ ਮਧਿ ਅੰਤਿ; ਨਿਰੰਕਾਰੰ॥", bani: "Bavan Akhri" },
  { tukh: "ਆਪਹਿ ਸੁੰਨ; ਆਪਹਿ ਸੁਖ ਆਸਨ॥", bani: "Bavan Akhri" },
  { tukh: "ਆਪਹਿ ਸੁਨਤ; ਆਪ ਹੀ ਜਾਸਨ॥", bani: "Bavan Akhri" },
  { tukh: "ਆਪਨਿ ਆਪੁ; ਆਪਹਿ ਉਪਾਇਓ॥", bani: "Bavan Akhri" },
  { tukh: "ਆਪਹਿ ਬਾਪ; ਆਪ ਹੀ ਮਾਇਓ॥", bani: "Bavan Akhri" },
  { tukh: "ਆਪਹਿ ਸੂਖਮ; ਆਪਹਿ ਅਸਥੂਲਾ॥", bani: "Bavan Akhri" },
  { tukh: "ਹਰਿ ਅੰਮ੍ਰਿਤ ਭਿੰਨੇ ਲੋਇਣਾ; ਮਨੁ ਪ੍ਰੇਮਿ ਰਤੰਨਾ ਰਾਮ ਰਾਜੇ॥", bani: "Asa Di Vaar" },
  { tukh: "ਮਨੁ. ਰਾਮਿ ਕਸਵਟੀ ਲਾਇਆ; ਕੰਚਨੁ ਸੋਵਿੰਨਾ॥", bani: "Asa Di Vaar" },
  { tukh: "ਗੁਰਮੁਖਿ ਰੰਗਿ ਚਲੂਲਿਆ; ਮੇਰਾ ਮਨੁ ਤਨੋ ਭਿੰਨਾ॥", bani: "Asa Di Vaar" },
  { tukh: "ਜਨੁ ਨਾਨਕੁ. ਮੁਸਕਿ ਝਕੋਲਿਆ; ਸਭੁ ਜਨਮੁ ਧਨੁ ਧੰਨਾ॥੧॥", bani: "Asa Di Vaar" },
  { tukh: "ਬਲਿਹਾਰੀ ਗੁਰ ਆਪਣੇ; ਦਿਉਹਾੜੀ ਸਦ ਵਾਰ॥", bani: "Asa Di Vaar" },
  { tukh: "ਜਿਨਿ. ਮਾਣਸ ਤੇ ਦੇਵਤੇ ਕੀਏ; ਕਰਤ. ਨ ਲਾਗੀ ਵਾਰ॥੧॥", bani: "Asa Di Vaar" },
  { tukh: "ਜੇ. ਸਉ ਚੰਦਾ ਉਗਵਹਿ; ਸੂਰਜ ਚੜਹਿ ਹਜਾਰ॥", bani: "Asa Di Vaar" },
  { tukh: "ਏਤੇ ਚਾਨਣ ਹੋਦਿਆਂ; ਗੁਰ ਬਿਨੁ. ਘੋਰ ਅੰਧਾਰ॥੨॥", bani: "Asa Di Vaar" },
  { tukh: "ਨਾਨਕ. ਗੁਰੂ ਨ ਚੇਤਨੀ; ਮਨਿ ਆਪਣੈ ਸੁਚੇਤ॥", bani: "Asa Di Vaar" },
  { tukh: "ਛੁਟੇ ਤਿਲ ਬੂਆੜ ਜਿਉ; ਸੁੰਞੇ ਅੰਦਰਿ ਖੇਤ॥", bani: "Asa Di Vaar" },
  { tukh: "ਖੇਤੈ ਅੰਦਰਿ ਛੁਟਿਆ; ਕਹੁ ਨਾਨਕ. ਸਉ ਨਾਹ॥", bani: "Asa Di Vaar" },
  { tukh: "ਫਲੀਅਹਿ ਫੁਲੀਅਹਿ ਬਪੁੜੇ; ਭੀ. ਤਨ ਵਿਚਿ ਸੁਆਹ॥੩॥", bani: "Asa Di Vaar" },
  { tukh: "ਆਪੀਨੑੈ ਆਪੁ ਸਾਜਿਓ; ਆਪੀਨੑੈ ਰਚਿਓ ਨਾਉ॥", bani: "Asa Di Vaar" },
  { tukh: "ਦੁਯੀ. ਕੁਦਰਤਿ ਸਾਜੀਐ; ਕਰਿ ਆਸਣੁ ਡਿਠੋ ਚਾਉ॥", bani: "Asa Di Vaar" },
  { tukh: "ਦਾਤਾ ਕਰਤਾ. ਆਪਿ ਤੂੰ; ਤੁਸਿ ਦੇਵਹਿ. ਕਰਹਿ ਪਸਾਉ॥", bani: "Asa Di Vaar" },
  { tukh: "ਤੂੰ ਜਾਣੋਈ ਸਭਸੈ; ਦੇ ਲੈਸਹਿ. ਜਿੰਦੁ ਕਵਾਉ॥", bani: "Asa Di Vaar" },
  { tukh: "ਕਰਿ ਆਸਣੁ; ਡਿਠੋ ਚਾਉ॥੧॥", bani: "Asa Di Vaar" },
  { tukh: "ਹਰਿ ਪ੍ਰੇਮ ਬਾਣੀ. ਮਨੁ ਮਾਰਿਆ; ਅਣੀਆਲੇ ਅਣੀਆ. ਰਾਮ ਰਾਜੇ॥", bani: "Asa Di Vaar" },
  { tukh: "ਦੁਖ ਭੰਜਨੁ. ਤੇਰਾ ਨਾਮੁ ਜੀ; ਦੁਖ ਭੰਜਨੁ. ਤੇਰਾ ਨਾਮੁ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਆਠ ਪਹਰ ਆਰਾਧੀਐ; ਪੂਰਨ ਸਤਿਗੁਰ ਗਿਆਨੁ॥੧॥ਰਹਾਉ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਜਿਤੁ ਘਟਿ ਵਸੈ ਪਾਰਬ੍ਰਹਮੁ; ਸੋਈ ਸੁਹਾਵਾ ਥਾਉ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਜਮਕੰਕਰੁ. ਨੇੜਿ ਨ ਆਵਈ; ਰਸਨਾ ਹਰਿ ਗੁਣ ਗਾਉ॥੧॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਸੇਵਾ ਸੁਰਤਿ. ਨ ਜਾਣੀਆ; ਨਾ ਜਾਪੈ ਆਰਾਧਿ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਓਟਿ ਤੇਰੀ ਜਗਜੀਵਨਾ; ਮੇਰੇ ਠਾਕੁਰ ਅਗਮ ਅਗਾਧਿ॥੨॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਭਏ ਕ੍ਰਿਪਾਲ ਗੁਸਾਈਆ; ਨਠੇ ਸੋਗ ਸੰਤਾਪ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਤਤੀ ਵਾਉ. ਨ ਲਗਈ; ਸਤਿਗੁਰਿ ਰਖੇ ਆਪਿ॥੩॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਗੁਰੁ ਨਾਰਾਇਣੁ. ਦਯੁ ਗੁਰੁ; ਗੁਰੁ ਸਚਾ ਸਿਰਜਣਹਾਰੁ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਗੁਰਿ ਤੁਠੈ. ਸਭ ਕਿਛੁ ਪਾਇਆ; ਜਨ ਨਾਨਕ. ਸਦ ਬਲਿਹਾਰ॥੪॥੨॥੧੭੦॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਕੀਤਾ ਲੋੜੀਐ ਕੰਮੁ; ਸੁ ਹਰਿ ਪਹਿ ਆਖੀਐ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਕਾਰਜੁ ਦੇਇ ਸਵਾਰਿ; ਸਤਿਗੁਰ ਸਚੁ ਸਾਖੀਐ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਸੰਤਾ ਸੰਗਿ ਨਿਧਾਨੁ; ਅੰਮ੍ਰਿਤੁ ਚਾਖੀਐ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਭੈ ਭੰਜਨ ਮਿਹਰਵਾਨ; ਦਾਸ ਕੀ ਰਾਖੀਐ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਨਾਨਕ. ਹਰਿ ਗੁਣ ਗਾਇ; ਅਲਖੁ ਪ੍ਰਭੁ ਲਾਖੀਐ॥੨੦॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਸੂਕੇ ਹਰੇ ਕੀਏ; ਖਿਨ ਮਾਹੇ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਅੰਮ੍ਰਿਤ ਦ੍ਰਿਸਟਿ ਸੰਚਿ; ਜੀਵਾਏ॥੧॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਕਾਟੇ ਕਸਟ; ਪੂਰੇ ਗੁਰਦੇਵ॥", bani: "Dukh Bhanjani Sahib" },
  { tukh: "ਕਬੀਰ. ਮੇਰੀ ਸਿਮਰਨੀ; ਰਸਨਾ ਊਪਰਿ ਰਾਮੁ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਆਦਿ ਜੁਗਾਦੀ ਸਗਲ ਭਗਤ; ਤਾ ਕੋ ਸੁਖੁ ਬਿਸ੍ਰਾਮੁ॥੧॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਮੇਰੀ ਜਾਤਿ ਕਉ; ਸਭੁ ਕੋ ਹਸਨੇਹਾਰੁ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਬਲਿਹਾਰੀ ਇਸ ਜਾਤਿ ਕਉ; ਜਿਹ ਜਪਿਓ ਸਿਰਜਨਹਾਰੁ॥੨॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਡਗਮਗ ਕਿਆ ਕਰਹਿ; ਕਹਾ ਡੁਲਾਵਹਿ ਜੀਉ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਸਰਬ ਸੂਖ ਕੋ ਨਾਇਕੋ; ਰਾਮ ਨਾਮ ਰਸੁ ਪੀਉ॥੩॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਕੰਚਨ ਕੇ ਕੁੰਡਲ ਬਨੇ; ਊਪਰਿ ਲਾਲ ਜੜਾਉ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਦੀਸਹਿ. ਦਾਧੇ ਕਾਨ ਜਿਉ; ਜਿਨੑ ਮਨਿ. ਨਾਹੀ ਨਾਉ॥੪॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਐਸਾ ਏਕੁ ਆਧੁ; ਜੋ ਜੀਵਤ ਮਿਰਤਕੁ ਹੋਇ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਨਿਰਭੈ ਹੋਇ ਕੈ ਗੁਨ ਰਵੈ; ਜਤ ਪੇਖਉ ਤਤ ਸੋਇ॥੫॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਜਾ ਦਿਨ ਹਉ ਮੂਆ; ਪਾਛੈ ਭਇਆ ਅਨੰਦੁ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਮੋਹਿ. ਮਿਲਿਓ ਪ੍ਰਭੁ ਆਪਨਾ; ਸੰਗੀ ਭਜਹਿ ਗੋੁਬਿੰਦੁ॥੬॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਸਭ ਤੇ ਹਮ ਬੁਰੇ; ਹਮ ਤਜਿ. ਭਲੋ ਸਭੁ ਕੋਇ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਜਿਨਿ ਐਸਾ ਕਰਿ ਬੂਝਿਆ; ਮੀਤੁ ਹਮਾਰਾ ਸੋਇ॥੭॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਆਈ ਮੁਝਹਿ ਪਹਿ; ਅਨਿਕ ਕਰੇ ਕਰਿ ਭੇਸ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਹਮ ਰਾਖੇ. ਗੁਰ ਆਪਨੇ; ਉਨਿ ਕੀਨੋ ਆਦੇਸੁ॥੮॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਕਬੀਰ. ਸੋਈ ਮਾਰੀਐ; ਜਿਹ ਮੂਐ ਸੁਖੁ ਹੋਇ॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਭਲੋ ਭਲੋ ਸਭੁ ਕੋ ਕਹੈ; ਬੁਰੋ. ਨ ਮਾਨੈ ਕੋਇ॥੯॥", bani: "Salok Bhagat Kabir" },
  { tukh: "ਜਿਤੁ ਦਿਹਾੜੈ. ਧਨ ਵਰੀ; ਸਾਹੇ ਲਏ ਲਿਖਾਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਮਲਕੁ. ਜਿ ਕੰਨੀ ਸੁਣੀਦਾ; ਮੁਹੁ ਦੇਖਾਲੇ ਆਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਜਿੰਦੁ ਨਿਮਾਣੀ ਕਢੀਐ; ਹਡਾ ਕੂ ਕੜਕਾਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਸਾਹੇ ਲਿਖੇ. ਨ ਚਲਨੀ; ਜਿੰਦੂ ਕੂੰ ਸਮਝਾਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਜਿੰਦੁ ਵਹੁਟੀ. ਮਰਣੁ ਵਰੁ; ਲੈ ਜਾਸੀ ਪਰਣਾਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਆਪਣ ਹਥੀ. ਜੋਲਿ ਕੈ; ਕੈ ਗਲਿ ਲਗੈ ਧਾਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਵਾਲਹੁ ਨਿਕੀ ਪੁਰ ਸਲਾਤ; ਕੰਨੀ. ਨ ਸੁਣੀਆਇ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਫਰੀਦਾ. ਕਿੜੀ ਪਵੰਦੀਈ; ਖੜਾ. ਨ ਆਪੁ ਮੁਹਾਇ॥੧॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਫਰੀਦਾ. ਦਰ ਦਰਵੇਸੀ ਗਾਖੜੀ; ਚਲਾਂ ਦੁਨੀਆਂ ਭਤਿ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਬੰਨਿੑ ਉਠਾਈ ਪੋਟਲੀ; ਕਿਥੈ ਵੰਞਾ ਘਤਿ॥੨॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਕਿਝੁ. ਨ ਬੁਝੈ, ਕਿਝੁ. ਨ ਸੁਝੈ; ਦੁਨੀਆ ਗੁਝੀ ਭਾਹਿ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਸਾਂਈਂ ਮੇਰੈ ਚੰਗਾ ਕੀਤਾ; ਨਾਹੀ ਤ, ਹੰ ਭੀ ਦਝਾਂ ਆਹਿ॥੩॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਫਰੀਦਾ. ਜੇ ਜਾਣਾ ਤਿਲ ਥੋੜੜੇ; ਸੰਮਲਿ ਬੁਕੁ ਭਰੀ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਜੇ ਜਾਣਾ ਸਹੁ ਨੰਢੜਾ; ਤਾਂ. ਥੋੜਾ ਮਾਣੁ ਕਰੀ॥੪॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਜੇ ਜਾਣਾ ਲੜੁ ਛਿਜਣਾ; ਪੀਡੀ ਪਾਈਂ ਗੰਢਿ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਤੈ ਜੇਵਡੁ. ਮੈ ਨਾਹਿ ਕੋ; ਸਭੁ ਜਗੁ ਡਿਠਾ ਹੰਢਿ॥੫॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਫਰੀਦਾ. ਜੇ ਤੂ ਅਕਲਿ ਲਤੀਫੁ; ਕਾਲੇ ਲਿਖੁ. ਨ ਲੇਖੁ॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਆਪਨੜੇ ਗਿਰੀਵਾਨ ਮਹਿ; ਸਿਰੁ ਨੀਂਵਾਂ ਕਰਿ ਦੇਖੁ॥੬॥", bani: "Salok Bhagat Farid" },
  { tukh: "ਅਕਾਲਪੁਰਖ ਕੀ; ਰਛਾ ਹਮਨੈ॥", bani: "Chaupai Sahib" },
  { tukh: "ਸਰਬ ਲੋਹ ਦੀ; ਰਛਿਆ ਹਮਨੈ॥", bani: "Chaupai Sahib" },
  { tukh: "ਸਰਬ ਕਾਲ ਜੀ ਦੀ; ਰਛਿਆ ਹਮਨੈ॥", bani: "Chaupai Sahib" },
  { tukh: "ਸਰਬ ਲੋਹ ਜੀ ਦੀ; ਸਦਾ ਰਛਿਆ ਹਮਨੈ॥", bani: "Chaupai Sahib" },
  { tukh: "ਜਲ ਥਲ ਮਹੀਅਲ ਕੀਓ ਪਸਾਰਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਆਦਿ ਪੁਰਖ ਅਬਗਤ ਅਬਿਨਾਸੀ॥", bani: "Chaupai Sahib" },
  { tukh: "ਲੋਕ ਚੱਤ੍ਰੁਦਸ ਜੋਤਿ ਪ੍ਰਕਾਸੀ॥੧॥", bani: "Chaupai Sahib" },
  { tukh: "ਹਸਤ ਕੀਟ ਕੇ ਬੀਚ ਸਮਾਨਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਰਾਵ ਰੰਕ ਜਿਹ ਇਕਸਰ ਜਾਨਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਅਦ੍ਵੈ ਅਲਖ ਪੁਰਖ ਅਬਿਗਾਮੀ॥", bani: "Chaupai Sahib" },
  { tukh: "ਸਭ ਘਟ ਘਟ ਕੇ ਅੰਤਰਜਾਮੀ॥੨॥", bani: "Chaupai Sahib" },
  { tukh: "ਅਲਖ ਰੂਪ ਅੱਛੈ ਅਨਭੇਖਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਬਰਨ ਚਿਹਨ ਸਭਹੂੰ ਤੇ ਨਿਆਰਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਆਦ ਪੁਰਖ ਅਦ੍ਵੈ ਅਬਿਕਾਰਾ॥੩॥", bani: "Chaupai Sahib" },
  { tukh: "ਬਰਨ ਚਿਹਨ ਜਿਹ ਜਾਤ ਨ ਪਾਤਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਸੱਤ੍ਰ ਮਿੱਤ੍ਰ ਜਿਹ ਤਾਤ ਨਾ ਮਾਤਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਸਭ ਤੇ ਦੂਰਿ ਸਭਨ ਤੇ ਨੇਰਾ॥", bani: "Chaupai Sahib" },
  { tukh: "ਜਲ ਥਲ ਮਹੀਅਲ ਜਾਹਿ ਬਸੇਰਾ॥੪॥", bani: "Chaupai Sahib" },
  { tukh: "ਅਨਾਜੁ ਮਗਉ; ਸਤ ਸੀਕਾ॥੧॥", bani: "Aarti" },
  { tukh: "ਇਕ ਤਾਜਨਿ ਤੁਰੀ ਚੰਗੇਰੀ॥", bani: "Aarti" },
  { tukh: "ਊਤਮੁ ਦੀਅਰਾ; ਨਿਰਮਲ ਬਾਤੀ॥", bani: "Aarti" },
  { tukh: "ਗਊ ਭੈਸ ਮਗਉ ਲਾਵੇਰੀ॥", bani: "Aarti" },
  { tukh: "ਗੁਰ ਸਾਖੀ; ਜੋਤਿ ਪਰਗਟੁ ਹੋਇ॥", bani: "Aarti" },
  { tukh: "ਗੋਪਾਲ ਤੇਰਾ ਆਰਤਾ॥", bani: "Aarti" },
  { tukh: "ਘਰ ਕੀ ਗੀਹਨਿ ਚੰਗੀ॥", bani: "Aarti" },
  { tukh: "ਜਨੁ ਧੰਨਾ ਲੇਵੈ ਮੰਗੀ॥੨॥੪॥", bani: "Aarti" },
  { tukh: "ਦਾਲਿ ਸੀਧਾ; ਮਾਗਉ ਘੀਉ॥", bani: "Aarti" },
  { tukh: "ਧੂਪ ਦੀਪ ਘ੍ਰਿਤ ਸਾਜਿ ਆਰਤੀ॥", bani: "Aarti" },
  { tukh: "ਪਨੑੀਆ ਛਾਦਨੁ ਨੀਕਾ॥", bani: "Aarti" },
  { tukh: "ਪੂਰਨ ਪਰਮਾਨੰਦੁ ਬਖਾਨੈ॥੩॥", bani: "Aarti" },
  { tukh: "ਪ੍ਰਭਾਤੀ॥", bani: "Aarti" },
  { tukh: "ਮੰਗਲਾ ਹਰਿ ਮੰਗਲਾ॥", bani: "Aarti" },
  { tukh: "ਰਾਮਾ ਭਗਤਿ ਰਾਮਾਨੰਦੁ ਜਾਨੈ॥", bani: "Aarti" },
  { tukh: "ਸ੍ਰਾਵਗ ਸੁਧ ਸਮੂਹ ਸਿਧਾਨ ਕੇ; ਦੇਖਿ ਫਿਰਿਓ ਘਰ ਜੋਗ ਜਤੀ ਕੇ॥", bani: "Tva Prasad Svaiye" },
  { tukh: "ਮਾਟੀ ਕੋ ਪੁਤਰਾ. ਕੈਸੇ ਨਚਤੁ ਹੈ॥", bani: "Tva Prasad Svaiye" },
  { tukh: "ਭਵਜਲ ਵਿਚੋਂ ਕਢਿ ਕੇ; ਮੁਕਤਿ ਪਦਾਰਥ ਮਾਹਿ ਸਮਾਇਆ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਜਨਮ ਮਰਣ ਭਉ ਕਟਿਆ; ਸੰਸਾ ਰੋਗ ਵਿਯੋਗ ਮਿਟਾਇਆ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਸੰਸਾ. ਇਹੁ ਸੰਸਾਰੁ ਹੈ; ਜਨਮ ਮਰਣ ਵਿਚਿ ਦੁਖ ਸਬਾਇਆ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਜਮਦੰਡ ਸਿਰੋਂ ਨਾ ਉਤਰੈ; ਸਾਕਤ ਦੁਰਜਨ ਜਨਮੁ ਗਵਾਇਆ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਚਰਨ ਗਹੇ ਗੁਰਦੇਵ ਦੇ; ਸਤਿ ਸਬਦ ਦੇ ਮੁਕਤ ਕਰਾਇਆ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਭਾਉ ਭਗਤਿ ਗੁਰਪੁਰਬ ਕਰਿ; ਨਾਮ ਦਾਨ ਇਸਨਾਨ ਦ੍ਰਿੜ੍ਹਾਇਆ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਜੇਹਾ ਬੀਉ; ਤੇਹਾ ਫਲੁ ਪਾਇਆ॥੧॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਪ੍ਰਿਥਮੈ. ਸਾਸ ਨ ਮਾਸ ਸਨ; ਅੰਧ ਧੁੰਧ ਕਛੁ ਖਬਰ ਨ ਪਾਈ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਰਕਤਬਿੰਦ ਕੀ ਦੇਹਿ ਰਚਿ; ਪਾਂਚ ਤਤ ਕੀ ਜੜਤ ਜੜਾਈ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਪਉਣ ਪਾਣੀ ਬੈਸੰਤਰੋ; ਚਉਥੀ ਧਰਤੀ ਸੰਗਿ ਮਿਲਾਈ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਪੰਚਮਿ ਵਿਚਿ ਆਕਾਸ ਕਰਿ; ਕਰਤਾ ਛਟਮੁ ਅਦਿਸਟੁ ਸਮਾਈ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਪੰਚ. ਤਤ ਪੰਚੀਸਿ ਗੁਨਿ; ਸਤ੍ਰ ਮਿਤ੍ਰ ਮਿਲਿ ਦੇਹਿ ਬਣਾਈ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਖਾਣੀ ਬਾਣੀ ਚਲਿਤੁ ਕਰਿ; ਆਵਾਗਉਣੁ ਚਰਿਤ੍ਰ ਦਿਖਾਈ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਚਉਰਾਸੀਹ ਲਖ; ਜੋਨਿ ਉਪਾਈ॥੨॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਚਉਰਾਸੀਹ ਲਖ ਜੋਨਿ ਵਿਚਿ; ਉਤਮੁ ਜਨਮੁ ਸੁ ਮਾਣਸਿ ਦੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਅਖੀ ਵੇਖਣੁ ਕਰਨਿ ਸੁਣਿ; ਮੁਖਿ ਸੁਭ ਬੋਲਣੁ ਬਚਨ ਸਨੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਹਥੀ ਕਾਰ ਕਮਾਵਣੀ; ਪੈਰੀ ਚਲਿ ਸਤਿਸੰਗਿ ਮਿਲੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਕਿਰਤਿ ਵਿਰਤਿ ਕਰਿ ਧਰਮ ਦੀ; ਖਟਿ ਖਵਾਲਣੁ ਕਾਰਿ ਕਰੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਗੁਰਮੁਖਿ ਜਨਮੁ ਸਕਾਰਥਾ; ਗੁਰਬਾਣੀ ਪੜਿ. ਸਮਝਿ ਸੁਣੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਗੁਰਭਾਈ ਸੰਤੁਸਟਿ ਕਰਿ; ਚਰਣਾਮ੍ਰਿਤੁ ਲੈ ਮੁਖਿ ਪਿਵੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਪੈਰੀ ਪਵਣੁ ਨ ਛੋਡੀਐ; ਕਲੀ ਕਾਲਿ ਰਹਰਾਸਿ ਕਰੇਹੀ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਆਪਿ ਤਰੇ; ਗੁਰਸਿਖ ਤਰੇਹੀ॥੩॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਓਅੰਕਾਰੁ. ਆਕਾਰੁ ਕਰਿ; ਏਕ ਕਵਾਉ. ਪਸਾਉ ਪਸਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਪੰਜ ਤਤ. ਪਰਵਾਣੁ ਕਰਿ; ਘਟਿ ਘਟਿ ਅੰਦਰਿ ਤ੍ਰਿਭਵਣੁ ਸਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਕਾਦਰੁ ਕਿਨੇ ਨ ਲਖਿਆ; ਕੁਦਰਤਿ ਸਾਜਿ ਕੀਆ ਅਵਤਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਇਕ ਦੂ ਕੁਦਰਤਿ ਲਖ ਕਰਿ; ਲਖ ਬਿਅੰਤ ਅਸੰਖ ਅਪਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਰੋਮ ਰੋਮ ਵਿਚਿ ਰਖਿਓਨਿ; ਕਰਿ ਬ੍ਰਹਮੰਡਿ ਕਰੋੜਿ ਸੁਮਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਇਕਸ ਇਕਸ ਬ੍ਰਹਮੰਡਿ ਵਿਚਿ; ਦਸ ਦਸ ਕਰਿ ਅਵਤਾਰ ਉਤਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਕੇਤੇ ਬੇਦ ਬਿਆਸ ਕਰਿ; ਕਈ ਕਤੇਬ ਮੁਹੰਮਦ ਯਾਰਾ॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਕੁਦਰਤਿ ਇਕੁ; ਏਤਾ ਪਾਸਾਰਾ॥੪॥", bani: "Bhai Gurdas Vaaran" },
  { tukh: "ਵਗਰਨਹ ਜ਼ੋਕ਼ਿ ਚੁਨੀਂ, ਆਮਦਨ ਨਬੂਦ ਮਰਾ॥੧॥", bani: "Bhai Nand Lal" },
  { tukh: "ਖ਼ੁਸ਼ ਅਸਤ ਉ਼ਮਰ, ਕਿਹ ਦਰ ਯਾਦਿ ਬੁਗਜ਼ਰਦ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਵਰਨਹ ਚਿ ਹ਼ਾਸਿਲ ਅਸਤ, ਅਜ਼ੀਂ ਗੁੰਬਜ਼ਿ ਕਬੂਦ ਮਰਾ॥੨॥", bani: "Bhai Nand Lal" },
  { tukh: "ਦਰ ਆਂ ਜ਼ਮਾਂ, ਕਿ ਨਿਆਈ ਯਾਦ ਮੇ-ਮੀਰਮ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਬਗ਼ੈਰ ਯਾਦਿ ਤੋ, ਜ਼ੀਂ ਜ਼ੀਸਤਨ, ਚਿਹ ਸੂਦ ਮਰਾ॥੩॥", bani: "Bhai Nand Lal" },
  { tukh: "ਫ਼ਿਦਾਸਤ, ਜਾਨੋ ਦਿਲਿ ਮਨ, ਬ-ਖ਼ਾਕਿ ਮਕ਼ੱਦਮਿ ਪਾਕ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਹਰ ਆਂ ਕਸੇ, ਕਿਹ ਬ-ਸੂਇ ਤੋ, ਰਹਿ ਨਮੂਦ ਮਰਾ॥੪॥", bani: "Bhai Nand Lal" },
  { tukh: "ਨਬੂਦ ਹੇਚ ਨਿਸ਼ਾਂਹਾ, ਜ਼ਿ ਆਸਮਾਨੋ ਜ਼ਮੀਂ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਕਿ ਸ਼ੌਕ਼ਿ ਰੂਇ ਤੋ, ਆਵੁਰਦ ਦਰ ਵਜੂਦ ਮਰਾ॥੫॥", bani: "Bhai Nand Lal" },
  { tukh: "ਬਗ਼ੈਰ ਯਾਦਿ ਤੋ, ਗੋਯਾ; ਨ ਮੇ-ਤਵਾਨਮ ਜ਼ੀਸਤ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਬਸੂਇ ਦੋਸਤ, ਰਹਾਈ ਦਿਹੰਦ, ਜ਼ੂਦ ਮਰਾ॥੬॥੧॥", bani: "Bhai Nand Lal" },
  { tukh: "ਗ਼ਜ਼ਲ ੨॥ ਦੀਨੋ ਦੁਨੀਆ, ਦਰ ਕਮੰਦਿ, ਆਂ ਪਰੀ ਰੁਖ਼ਸਾਰਿ ਮਾ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਹਰ ਦੋ ਆਲਮ ਕ਼ੀਮਤਿ, ਯੱਕ ਤਾਰਿ ਮੂਇ ਯਾਰਿ ਮਾ॥੧॥", bani: "Bhai Nand Lal" },
  { tukh: "ਮਾ ਨ ਮੇ-ਆਰੇਮ, ਤਾਬਿ ਗ਼ਮਜ਼ਾਇ ਮਿਜ਼ਗਾਨਿ ਊ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਯੱਕ ਨਿਗਾਹਿ ਜਾਂ-ਫਿਜ਼ਾਇਸ਼, ਬਸ ਬਵਦ ਦਰਕਾਰਿ ਮਾ॥੨॥", bani: "Bhai Nand Lal" },
  { tukh: "ਗਾਹੇ ਸੂਫ਼ੀ ਗਾਹੇ ਜ਼ਾਹਿਦ, ਗਹਿ ਕ਼ਲੰਦਰ ਮੇ ਸ਼ਵਦ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਰੰਗਹਾਇ ਮੁਖ਼ਤਲਿਫ਼, ਦਾਰਦ ਬੁੱਤਿ ਅੱਯਾਰਿ ਮਾ॥੩॥", bani: "Bhai Nand Lal" },
  { tukh: "ਕ਼ਦਰਿ ਲਾਅ਼ਲਿ ਊ, ਬਜੁਜ਼ ਆਸ਼ਿਕ਼, ਨਾ ਦਾਨਦ ਹੇਚਕਸ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਕ਼ੀਮਤਿ ਯਾਕ਼ੂਤ ਦਾਨਦ, ਚਸ਼ਮਿ ਗੌਹਰਬਾਰਿ ਮਾ॥੪॥", bani: "Bhai Nand Lal" },
  { tukh: "ਹਰ ਨਫ਼ਸ, ਗੋਯਾ ਬ-ਯਾਦਿ, ਨਰਗਿਸਿ ਮਖ਼ਮੂਰਿ ਊ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਬਾਦਾਹਾਇ ਸ਼ੌਕ਼ ਮੇ-ਨੋਸ਼ਦ, ਦਿਲਿ ਹੁਸ਼ਿਆਰਿ ਮਾ॥੫॥੨॥", bani: "Bhai Nand Lal" },
  { tukh: "ਗ਼ਜ਼ਲ ੩॥ ਬਿਦਿਹ ਸਾਕ਼ੀ, ਮਰਾ ਯੱਕ ਜਾਮ, ਜ਼ਾਂ ਰੰਗੀਨੀਇ ਦਿਲਹਾ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਬਚਸ਼ਮਿ ਪਾਕ-ਬੀਂ, ਆਸਾਂ ਕੁਨਮ, ਈਂ ਜੁਮਲਹ ਮੁਸ਼ਕਿਲਹਾ॥੧॥", bani: "Bhai Nand Lal" },
  { tukh: "ਮਰਾ ਦਰ ਮੰਜ਼ਿਲਿ ਜਾਨਾਂ, ਹਮਹ ਐ਼ਸ਼ੋ ਹਮਹ ਸ਼ਾਦੀ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਜਰਸ ਬੇਹੂਦਹ ਮੇ-ਨਾਲਦ, ਕੁਜਾ ਬੰਦੇਮ ਮਹ਼ਮਿਲਹਾ॥੨॥", bani: "Bhai Nand Lal" },
  { tukh: "ਖ਼ੁਦਾ ਹ਼ਾਜ਼ਿਰ ਬਵਦ ਦਾਇਮ, ਬਿਬੀਂ ਦੀਦਾਰਿ ਪਾਕਸ਼ ਰਾ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਨਾ ਗਿਰਦਾਬੇ ਦਰੋ ਹਾਇਲ, ਨਾ ਦਰਿਆਓ, ਨਾ ਸਾਹਿਲਹਾ॥੩॥", bani: "Bhai Nand Lal" },
  { tukh: "ਚਿਰਾ ਬੇਹੂਦਹ ਮੇ ਗਰਦੀ, ਬ-ਸਹਿਰਾਂ ਓ ਬ-ਦਸ਼ਤ, ਐ ਦਿਲ॥", bani: "Bhai Nand Lal" },
  { tukh: "ਚੂੰ ਆਂ ਸੁਲਤ਼ਾਨਿ ਖ਼ੂਬਾਂ, ਕਰਦਹ ਅੰਦਰ ਦੀਦਹ ਮੰਜ਼ਿਲਹਾ॥੪॥", bani: "Bhai Nand Lal" },
  { tukh: "ਚੂੰ ਗ਼ੈਰ ਅਜ਼ ਜ਼ਾਤਿ-ਪਾਕਿਸ਼ ਨੇਸਤ, ਦਰ ਹਰ ਜਾ ਕਿ ਮੇ-ਬੀਨਮ॥", bani: "Bhai Nand Lal" },
];

export const allBanis: string[] = Array.from(new Set(baniBank.map((b) => b.bani))).sort();

export const SOURCES = [
  "Sri Guru Granth Sahib Ji",
  "Dasam Granth Sahib Ji",
  "Bhai Gurdas Vaaran",
  "Bhai Nand Lal",
] as const;
export type Source = (typeof SOURCES)[number];

export function sourceFor(bani: string): Source {
  if (bani === "Jaap Sahib" || bani === "Chaupai Sahib" || bani === "Tva Prasad Svaiye") {
    return "Dasam Granth Sahib Ji";
  }
  if (bani === "Bhai Gurdas Vaaran") return "Bhai Gurdas Vaaran";
  if (bani === "Bhai Nand Lal") return "Bhai Nand Lal";
  return "Sri Guru Granth Sahib Ji";
}

export type TukhItem = {
  prefix: string;
  /** In normal mode this is the missing word. In `oddOneOut` mode this is
   *  the word that does NOT pair with the prefix; the rest do. */
  answer: string;
  suffix: string;
  distractors: string[];
  bani: string;
  oddOneOut?: boolean;
};

export const tukhBank: TukhItem[] = [
  // Fill in the blank
  { prefix: "ੴ ", answer: "ਸਤਿਨਾਮੁ", suffix: " ਕਰਤਾ ਪੁਰਖੁ॥",
    distractors: ["ਸਤਿਗੁਰ", "ਸਤਿ", "ਨਾਮੁ"], bani: "Mool Mantar" },
  { prefix: "ਆਦਿ ", answer: "ਸਚੁ", suffix: " ਜੁਗਾਦਿ ਸਚੁ॥",
    distractors: ["ਨਾਮੁ", "ਗੁਰੁ", "ਸਾਚਾ"], bani: "Japji Sahib" },
  { prefix: "ਸੋਚੈ ਸੋਚਿ ਨ ", answer: "ਹੋਵਈ", suffix: "॥",
    distractors: ["ਜਾਣੈ", "ਪਾਵਈ", "ਆਵੈ"], bani: "Japji Sahib" },
  { prefix: "ਸੁਖਮਨੀ ਸੁਖ ਅੰਮ੍ਰਿਤ ਪ੍ਰਭ ", answer: "ਨਾਮੁ", suffix: "॥",
    distractors: ["ਜਾਪੁ", "ਨਾਨਕ", "ਸਾਚਾ"], bani: "Sukhmani Sahib" },
  { prefix: "ਅਨੰਦੁ ਭਇਆ ਮੇਰੀ ", answer: "ਮਾਏ", suffix: "॥",
    distractors: ["ਜੀਉ", "ਮਾਤਾ", "ਪਿਆਰੇ"], bani: "Anand Sahib" },
  { prefix: "ਗਗਨ ਮੈ ", answer: "ਥਾਲੁ", suffix: "; ਰਵਿ ਚੰਦੁ ਦੀਪਕ ਬਨੇ॥",
    distractors: ["ਨਾਮੁ", "ਦੀਪਕ", "ਜੋਤਿ"], bani: "Aarti" },
  // Amrit Banis beyond Nitnem
  { prefix: "ਸਚੁ ", answer: "ਖਾਣਾ", suffix: "; ਸਚੁ ਪੈਨਣਾ; ਸਚੇ ਹੀ ਵਿਚਿ ਵਾਸੁ॥",
    distractors: ["ਜੀਵਣਾ", "ਬੋਲਣਾ", "ਚੰਗਾ"], bani: "Asa Di Vaar" },
  { prefix: "ਆਪੀਨੈੑ ਆਪੁ ", answer: "ਸਾਜਿਓ", suffix: "; ਆਪੀਨੈੑ ਰਚਿਓ ਨਾਉ॥",
    distractors: ["ਪਾਇਆ", "ਜਾਣਿਆ", "ਬੋਲਿਆ"], bani: "Asa Di Vaar" },
  { prefix: "ਦੁਖ ਭੰਜਨੁ ਤੇਰਾ ", answer: "ਨਾਮੁ", suffix: " ਜੀ॥",
    distractors: ["ਜਾਪੁ", "ਰੂਪੁ", "ਦਾਨੁ"], bani: "Dukh Bhanjani Sahib" },
  // Odd-one-out from Jaap Sahib (each distractor is a real Jaap namaskar)
  { prefix: "ਨਮਸਤੰ ", answer: "ਨਾਨਕਾ", suffix: "॥",
    distractors: ["ਅਕਾਲੇ", "ਕ੍ਰਿਪਾਲੇ", "ਅਰੂਪੇ"], bani: "Jaap Sahib", oddOneOut: true },
  { prefix: "ਨਮਸਤੰ ", answer: "ਮਾਤਾ", suffix: "॥",
    distractors: ["ਅਜੋਨੀ", "ਅਜਾਤੇ", "ਅਨਾਮੇ"], bani: "Jaap Sahib", oddOneOut: true },
  { prefix: "ਨਮੋ ਸਰਬ ", answer: "ਨਾਮੇ", suffix: "॥",
    distractors: ["ਕਾਲੇ", "ਦਿਆਲੇ", "ਰੂਪੇ"], bani: "Jaap Sahib", oddOneOut: true },
  { prefix: "ਆਦਿ ", answer: "ਸਚੁ", suffix: "; ਜੁਗਾਦਿ ਸਚੁ॥", distractors: ["ਅਸੰਖਾ", "ਤਨੋ", "ਜਾਸੁ"], bani: "Japji Sahib" },
  { prefix: "ਹੈ ਭੀ ", answer: "ਸਚੁ", suffix: "; ਨਾਨਕ ਹੋਸੀ ਭੀ ਸਚੁ॥੧॥", distractors: ["ਕੀਨੋ", "ਕਲੰਕੰ", "ਸੂਰਜ"], bani: "Japji Sahib" },
  { prefix: "ਸੋਚੈ. ਸੋਚਿ ਨ ਹੋਵਈ; ਜੇ ", answer: "ਸੋਚੀ", suffix: " ਲਖ ਵਾਰ॥", distractors: ["ਮਾਗਉ", "ਐਸਾ", "ਰਸਨਾ"], bani: "Japji Sahib" },
  { prefix: "ਚੁਪੈ. ਚੁਪਿ ਨ ਹੋਵਈ; ਜੇ ਲਾਇ ", answer: "ਰਹਾ", suffix: " ਲਿਵਤਾਰ॥", distractors: ["ਆਖੀਐ", "ਆਇਆ", "ਕਰਾ"], bani: "Japji Sahib" },
  { prefix: "ਭੁਖਿਆ. ਭੁਖ ਨ ", answer: "ਉਤਰੀ", suffix: "; ਜੇ ਬੰਨਾ ਪੁਰੀਆ ਭਾਰ॥", distractors: ["ਛਾਦਨੁ", "ਬ੍ਰਹਮਾ", "ਰਾਮ"], bani: "Japji Sahib" },
  { prefix: "ਸਹਸ ", answer: "ਸਿਆਣਪਾ", suffix: " ਲਖ ਹੋਹਿ; ਤ ਇਕ ਨ ਚਲੈ ਨਾਲਿ॥", distractors: ["ਸਾਖੀਐ", "ਜਾਹਿ", "ਹੋਵਨਿ"], bani: "Japji Sahib" },
  { prefix: "ਕਿਵ. ਸਚਿਆਰਾ ਹੋਈਐ; ਕਿਵ. ਕੂੜੈ ", answer: "ਤੁਟੈ", suffix: " ਪਾਲਿ॥", distractors: ["ਪਰਣਾਇ", "ਚਾਨਣ", "ਪਾਲਿ"], bani: "Japji Sahib" },
  { prefix: "ਹੁਕਮਿ ਰਜਾਈ ਚਲਣਾ; ", answer: "ਨਾਨਕ", suffix: " ਲਿਖਿਆ ਨਾਲਿ॥੧॥", distractors: ["ਅਣੀਆ", "ਸੋਇ॥੭", "ਹੋਸੀ"], bani: "Japji Sahib" },
  { prefix: "ਹੁਕਮੀ ਹੋਵਨਿ ", answer: "ਆਕਾਰ", suffix: "; ਹੁਕਮੁ. ਨ ਕਹਿਆ ਜਾਈ॥", distractors: ["ਸਵਾਰੇ", "ਪਰਹਰੈ", "ਦਿਹਾੜੈ"], bani: "Japji Sahib" },
  { prefix: "ਹੁਕਮੀ ਹੋਵਨਿ ਜੀਅ; ", answer: "ਹੁਕਮਿ", suffix: " ਮਿਲੈ ਵਡਿਆਈ॥", distractors: ["ਕੀਤਾ", "ਘਟਿ", "ਸਾਹਿਬਾ"], bani: "Japji Sahib" },
  { prefix: "ਹੁਕਮੀ ਉਤਮੁ ਨੀਚੁ; ", answer: "ਹੁਕਮਿ", suffix: " ਲਿਖਿ ਦੁਖ ਸੁਖ ਪਾਈਅਹਿ॥", distractors: ["ਕਥੈ", "ਏਕੋ", "ਦੇਖਿ"], bani: "Japji Sahib" },
  { prefix: "ਇਕਨਾ ", answer: "ਹੁਕਮੀ", suffix: " ਬਖਸੀਸ; ਇਕਿ ਹੁਕਮੀ ਸਦਾ ਭਵਾਈਅਹਿ॥", distractors: ["ਦਿਨ", "ਹੋਆ", "ਥੋੜੜੇ"], bani: "Japji Sahib" },
  { prefix: "ਹੁਕਮੈ ਅੰਦਰਿ ਸਭੁ ਕੋ; ", answer: "ਬਾਹਰਿ", suffix: " ਹੁਕਮ ਨ ਕੋਇ॥", distractors: ["ਸੋਇ॥੫", "ਆਕਾਰ", "ਸਮਝਾਇ"], bani: "Japji Sahib" },
  { prefix: "ਨਾਨਕ ਹੁਕਮੈ ਜੇ ਬੁਝੈ; ਤ ਹਉਮੈ ", answer: "ਕਹੈ", suffix: " ਨ ਕੋਇ॥੨॥", distractors: ["ਰਸਨਾ", "ਕਿਥੈ", "ਪਇਆ"], bani: "Japji Sahib" },
  { prefix: "ਗਾਵੈ ਕੋ ", answer: "ਤਾਣੁ", suffix: "; ਹੋਵੈ ਕਿਸੈ ਤਾਣੁ॥", distractors: ["ਮਾਹਿ", "ਤਤੀ", "ਲਿਵਤਾਰ"], bani: "Japji Sahib" },
  { prefix: "ਗਾਵੈ ਕੋ ਦਾਤਿ; ", answer: "ਜਾਣੈ", suffix: " ਨੀਸਾਣੁ॥", distractors: ["ਮੰਗਲਾ", "ਗੁਣ", "ਸਾਖੀ"], bani: "Japji Sahib" },
  { prefix: "ਗਾਵੈ ਕੋ; ", answer: "ਗੁਣ", suffix: " ਵਡਿਆਈਆ ਚਾਰ॥", distractors: ["ਆਪਿ॥੩", "ਸੁਆਮੀ", "ਜਪਿਓ"], bani: "Japji Sahib" },
  { prefix: "ਗਾਵੈ ਕੋ; ਵਿਦਿਆ ", answer: "ਵਿਖਮੁ", suffix: " ਵੀਚਾਰੁ॥", distractors: ["ਉਤਮੁ", "ਹੋਵਨਿ", "ਚਾਨਣ"], bani: "Japji Sahib" },
  { prefix: "ਚੱਕ੍ਰ ਚਿਹਨ ਅਰੁ ਬਰਨ ਜਾਤਿ; ਅਰੁ ਪਾਤਿ ", answer: "ਨਹਿਨ", suffix: " ਜਿਹ॥", distractors: ["ਕਰਹਿ", "ਨਾਇਕੋ", "ਜੁਗਾਦਿ"], bani: "Jaap Sahib" },
  { prefix: "ਅਚਲ ਮੂਰਤਿ ਅਨਭਉ ਪ੍ਰਕਾਸ; ", answer: "ਅਮਿਤੋਜ", suffix: " ਕਹਿੱਜੈ॥", distractors: ["ਹਮਨੈ", "ਪੂਰਨ", "ਚਾਖੀਐ"], bani: "Jaap Sahib" },
  { prefix: "ਕੋਟਿ ਇੰਦ੍ਰ ਇੰਦ੍ਰਾਣਿ; ", answer: "ਸਾਹਿ", suffix: " ਸਾਹਾਣਿ ਗਣਿੱਜੈ॥", distractors: ["ਦੂਖ", "ਘ੍ਰਿਤ", "ਸਚੁ॥੧"], bani: "Jaap Sahib" },
  { prefix: "ਤ੍ਵ ਸਰਬ ਨਾਮ. ", answer: "ਕਥੈ", suffix: " ਕਵਨ; ਕਰਮ ਨਾਮ ਬਰਨਤ ਸੁਮਤਿ॥੧॥", distractors: ["ਹਜਾਰ", "ਸੋਈ", "ਸਾਧ"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ", answer: "ਚੰਦ੍ਰ", suffix: " ਚੰਦ੍ਰੇ॥ਨਮੋ ਭਾਨ ਭਾਨੇ॥", distractors: ["ਮੇਰਿਆ", "ਰਾਖੇ", "ਕੋਇ॥੨"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ਗੀਤ ", answer: "ਗੀਤੇ", suffix: "; ਨਮੋ ਤਾਨ ਤਾਨੇ॥੪੭॥", distractors: ["ਕੋਊ", "ਪੁਰਾਨ", "ਨਹਿਨ"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ਨਿਰਤ ਨਿਰਤੇ; ", answer: "ਨਮੋ", suffix: " ਨਾਦ ਨਾਦੇ॥", distractors: ["ਸਾਖੀ", "ਸੋਦਰੁ", "ਰੰਕ"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ਪਾਨ ", answer: "ਪਾਨੇ", suffix: "; ਨਮੋ ਬਾਦ ਬਾਦੇ॥੪੮॥", distractors: ["ਸਮਝਾਇ", "ਥੋੜਾ", "ਸੋਹਿਲੈ"], bani: "Jaap Sahib" },
  { prefix: "ਅਨੰਗੀ ", answer: "ਅਨਾਮੇ", suffix: "; ਸਮਸਤੀ ਸਰੂਪੇ॥", distractors: ["ਚਾਉ", "ਸੰਗਿ", "ਅਸਥੂਲਾ"], bani: "Jaap Sahib" },
  { prefix: "ਪ੍ਰਭੰਗੀ ਪ੍ਰਮਾਥੇ; ", answer: "ਸਮਸਤੀ", suffix: " ਬਿਭੂਤੇ॥੪੯॥", distractors: ["ਨਸੈ", "ਜਾਤ", "ਆਵਈ"], bani: "Jaap Sahib" },
  { prefix: "ਕਲੰਕੰ ", answer: "ਬਿਨਾ", suffix: "; ਨੇਕਲੰਕੀ ਸਰੂਪੇ॥", distractors: ["ਮੂਐ", "ਸਾਹਿਬੁ", "ਤੇਰਾ"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ", answer: "ਰਾਜ", suffix: " ਰਾਜੇਸ੍ਵਰੰ; ਪਰਮ ਰੂਪੇ॥੫੦॥", distractors: ["ਸਿਮਰਉ", "ਮਾਣੁ", "ਪਹਰਾ"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ਜੋਗ ਜੋਗੇਸ੍ਵਰੰ; ", answer: "ਪਰਮ", suffix: " ਸਿੱਧੇ॥", distractors: ["ਬੰਧਿਪ", "ਕੂੜੈ", "ਜੋਤਿ"], bani: "Jaap Sahib" },
  { prefix: "ਅਭੇਖੀ ", answer: "ਅਭਰਮੀ", suffix: " ਅਭੋਗੀ ਅਭੁਗਤੇ॥", distractors: ["ਸਹਸ", "ਭੁਖਿਆ", "ਬੇਦ"], bani: "Jaap Sahib" },
  { prefix: "ਨਮੋ ਜੋਗ ", answer: "ਜੋਗੇਸ੍ਵਰੰ", suffix: "; ਪਰਮ ਜੁਗਤੇ॥੫੩॥", distractors: ["ਸਤਿਗੁਰਿ", "ਬਸੇਰਾ॥੪", "ਫੁਲੀਅਹਿ"], bani: "Jaap Sahib" },
  { prefix: "ਸ੍ਰੀ ", answer: "ਗੁਰਦੇਵ", suffix: " ਏ; ਨਮਹ॥੧॥", distractors: ["ਡਗਮਗ", "ਗਾਵਹੁ", "ਵਸਾਇਆ"], bani: "Sukhmani Sahib" },
  { prefix: "ਸਿਮਰਉ. ਸਿਮਰਿ ", answer: "ਸਿਮਰਿ", suffix: "; ਸੁਖੁ ਪਾਵਉ॥", distractors: ["ਏਕੈ", "ਸਾਜਿ", "ਆਦੇਸੁ॥੮"], bani: "Sukhmani Sahib" },
  { prefix: "ਕਲਿ ", answer: "ਕਲੇਸ", suffix: "; ਤਨ ਮਾਹਿ ਮਿਟਾਵਉ॥", distractors: ["ਕੁੰਡਲ", "ਲਿਖੇ", "ਕੋਇ"], bani: "Sukhmani Sahib" },
  { prefix: "ਸਿਮਰਉ ਜਾਸੁ; ", answer: "ਬਿਸੁੰਭਰ", suffix: " ਏਕੈ॥", distractors: ["ਸਿਫਤਿ", "ਆਧਾਰੋ", "ਫਰੀਦਾ"], bani: "Sukhmani Sahib" },
  { prefix: "ਨਾਮੁ ਜਪਤ; ", answer: "ਅਗਨਤ", suffix: " ਅਨੇਕੈ॥", distractors: ["ਰਾਖੁ", "ਪੋਟਲੀ", "ਭੰਜਨ"], bani: "Sukhmani Sahib" },
  { prefix: "ਬੇਦ ਪੁਰਾਨ; ", answer: "ਸਿੰਮ੍ਰਿਤਿ", suffix: " ਸੁਧਾਖੵਰ॥", distractors: ["ਲਖਿਆ॥੧॥ਰਹਾਉ", "ਅਗਾਧਿ॥੨", "ਸੁਮਾਰੁ॥੨"], bani: "Sukhmani Sahib" },
  { prefix: "ਕੀਨੇ ", answer: "ਰਾਮ", suffix: " ਨਾਮ; ਇਕ ਆਖੵਰ॥", distractors: ["ਸੋਇ॥੭", "ਰਵੈ", "ਜੜਾਉ"], bani: "Sukhmani Sahib" },
  { prefix: "ਕਿਨਕਾ ਏਕ; ਜਿਸੁ ", answer: "ਜੀਅ", suffix: " ਬਸਾਵੈ॥", distractors: ["ਕਹੁ", "ਤੇਰਾ", "ਬਰਨ"], bani: "Sukhmani Sahib" },
  { prefix: "ਤਾ ਕੀ ", answer: "ਮਹਿਮਾ", suffix: "; ਗਨੀ ਨ ਆਵੈ॥", distractors: ["ਪਵੈ", "ਅਗਮ", "ਸਬਦਿ"], bani: "Sukhmani Sahib" },
  { prefix: "ਕਾਂਖੀ; ਏਕੈ ", answer: "ਦਰਸ", suffix: " ਤੁਹਾਰੋ॥", distractors: ["ਮਾਨੈ", "ਗੁਝੀ", "ਮਿਲਿਓ"], bani: "Sukhmani Sahib" },
  { prefix: "ਨਾਨਕ. ਉਨ ", answer: "ਸੰਗਿ", suffix: "; ਮੋਹਿ ਉਧਾਰੋ॥੧॥", distractors: ["ਲਿਖਿ", "ਤਾਜਨਿ", "ਵਡਾਈ"], bani: "Sukhmani Sahib" },
  { prefix: "ਸੁਖਮਨੀ ਸੁਖ; ਅੰਮ੍ਰਿਤ ", answer: "ਪ੍ਰਭ", suffix: " ਨਾਮੁ॥", distractors: ["ਰੇਖ", "ਗੁਰੂ", "ਕੁਦਰਤਿ"], bani: "Sukhmani Sahib" },
  { prefix: "ਭਗਤ ਜਨਾ ਕੈ; ", answer: "ਮਨਿ", suffix: " ਬਿਸ੍ਰਾਮ॥ਰਹਾਉ॥", distractors: ["ਖੜਾ", "ਰਹਿਆ", "ਰਛਾ"], bani: "Sukhmani Sahib" },
  { prefix: "ਪ੍ਰਭ ਕੈ ", answer: "ਸਿਮਰਨਿ", suffix: "; ਗਰਭਿ ਨ ਬਸੈ॥", distractors: ["ਸੁਮਤਿ॥੧", "ਨੰਢੜਾ", "ਰੰਗਿ"], bani: "Sukhmani Sahib" },
  { prefix: "ਪ੍ਰਭ ਕੈ ਸਿਮਰਨਿ; ", answer: "ਦੁਸਮਨੁ", suffix: " ਟਰੈ॥", distractors: ["ਨਿਮਾਣੀ", "ਤੇਰੇ", "ਆਰਾਧੀਐ"], bani: "Sukhmani Sahib" },
  { prefix: "ਪ੍ਰਭ ", answer: "ਸਿਮਰਤ", suffix: "; ਕਛੁ ਬਿਘਨੁ ਨ ਲਾਗੈ॥", distractors: ["ਭੰਜਨੁ", "ਉਠਾਈ", "ਉਪਦੇਸੈ"], bani: "Sukhmani Sahib" },
  { prefix: "ਸਤਿਗੁਰੁ. ਤ ਪਾਇਆ ਸਹਜ ਸੇਤੀ; ", answer: "ਮਨਿ", suffix: " ਵਜੀਆ ਵਾਧਾਈਆ॥", distractors: ["ਉਪਾਇਆ", "ਰਜਾਈ", "ਕਿਥੈ"], bani: "Anand Sahib" },
  { prefix: "ਸਬਦੋ ਤ ਗਾਵਹੁ ", answer: "ਹਰੀ", suffix: " ਕੇਰਾ; ਮਨਿ ਜਿਨੀ ਵਸਾਇਆ॥", distractors: ["ਸਿਰੁ", "ਭੁਖ", "ਰਾਮ"], bani: "Anand Sahib" },
  { prefix: "ਕਹੈ ਨਾਨਕੁ. ", answer: "ਅਨੰਦੁ", suffix: " ਹੋਆ; ਸਤਿਗੁਰੂ. ਮੈ ਪਾਇਆ॥੧॥", distractors: ["ਜਾਣੈ", "ਬਿਸੁੰਭਰ", "ਮੂੜ"], bani: "Anand Sahib" },
  { prefix: "ਏ ਮਨ ਮੇਰਿਆ; ਤੂ ਸਦਾ ਰਹੁ ", answer: "ਹਰਿ", suffix: " ਨਾਲੇ॥", distractors: ["ਚੜਹਿ", "ਰਹਾ", "ਸੋਹਨਿ"], bani: "Anand Sahib" },
  { prefix: "ਹਰਿ ਨਾਲਿ ", answer: "ਰਹੁ", suffix: " ਤੂ ਮੰਨ ਮੇਰੇ; ਦੂਖ ਸਭਿ ਵਿਸਾਰਣਾ॥", distractors: ["ਹੁਕਮੀ", "ਦਾਧੇ", "ਪਾਈਂ"], bani: "Anand Sahib" },
  { prefix: "ਅੰਗੀਕਾਰੁ ਓਹੁ ਕਰੇ ", answer: "ਤੇਰਾ", suffix: "; ਕਾਰਜ ਸਭਿ ਸਵਾਰਣਾ॥", distractors: ["ਪਾਈਅਹਿ", "ਭਾਨ", "ਪਾਵਹੁ"], bani: "Anand Sahib" },
  { prefix: "ਸਭਨਾ ", answer: "ਗਲਾ", suffix: " ਸਮਰਥੁ ਸੁਆਮੀ; ਸੋ. ਕਿਉ ਮਨਹੁ ਵਿਸਾਰੇ॥", distractors: ["ਜਿਨ", "ਜਨੁ", "ਉਤਮੁ"], bani: "Anand Sahib" },
  { prefix: "ਕਹੈ ਨਾਨਕੁ. ਮੰਨ ", answer: "ਮੇਰੇ", suffix: "; ਸਦਾ ਰਹੁ ਹਰਿ ਨਾਲੇ॥੨॥", distractors: ["ਅਭਰਮੀ", "ਰਵੈ", "ਮਾਹੁ"], bani: "Anand Sahib" },
  { prefix: "ਸਾਚੇ ਸਾਹਿਬਾ; ", answer: "ਕਿਆ", suffix: " ਨਾਹੀ. ਘਰਿ ਤੇਰੈ॥", distractors: ["ਵਸਿਆ", "ਛੁਟੇ", "ਅਦ੍ਵੈ"], bani: "Anand Sahib" },
  { prefix: "ਸਦਾ ", answer: "ਸਿਫਤਿ", suffix: " ਸਲਾਹ ਤੇਰੀ; ਨਾਮੁ ਮਨਿ ਵਸਾਵਏ॥", distractors: ["ਸਗਲ", "ਰਹਿਆ", "ਆਪਿ॥੩"], bani: "Anand Sahib" },
  { prefix: "ਨਾਮੁ ਜਿਨ ਕੈ ", answer: "ਮਨਿ", suffix: " ਵਸਿਆ; ਵਾਜੇ ਸਬਦ ਘਨੇਰੇ॥", distractors: ["ਉਪਦੇਸ", "ਆਖੀਐ", "ਦੂਖੁ"], bani: "Anand Sahib" },
  { prefix: "ਕਹੈ ", answer: "ਨਾਨਕੁ", suffix: ". ਸਚੇ ਸਾਹਿਬ; ਕਿਆ ਨਾਹੀ. ਘਰਿ ਤੇਰੈ॥੩॥", distractors: ["ਬਸੇਰਾ॥੪", "ਚੁਪੈ", "ਜਿਤੁ"], bani: "Anand Sahib" },
  { prefix: "ਸਾਚਾ ਨਾਮੁ; ", answer: "ਮੇਰਾ", suffix: " ਆਧਾਰੋ॥", distractors: ["ਚਲੂਲਿਆ", "ਮਹਲਾ", "ਕਿਆ"], bani: "Anand Sahib" },
  { prefix: "ਸਾਚੁ ਨਾਮੁ ਅਧਾਰੁ ਮੇਰਾ; ਜਿਨਿ ਭੁਖਾ ", answer: "ਸਭਿ", suffix: " ਗਵਾਈਆ॥", distractors: ["ਲਿਖਿ", "ਲੈਸਹਿ", "ਭਿੰਨਾ"], bani: "Anand Sahib" },
  { prefix: "ਸਦਾ ਕੁਰਬਾਣੁ ", answer: "ਕੀਤਾ", suffix: " ਗੁਰੂ ਵਿਟਹੁ; ਜਿਸ ਦੀਆ ਏਹਿ ਵਡਿਆਈਆ॥", distractors: ["ਹਮਨੈ", "ਪ੍ਰੇਮਿ", "ਹੋਹਿ"], bani: "Anand Sahib" },
  { prefix: "ਕਹੈ ਨਾਨਕੁ. ਸੁਣਹੁ ਸੰਤਹੁ; ", answer: "ਸਬਦਿ", suffix: " ਧਰਹੁ ਪਿਆਰੋ॥", distractors: ["ਗੀਹਨਿ", "ਕਬੀਰ", "ਕਰਤਾ"], bani: "Anand Sahib" },
  { prefix: "ਹਰਣਾਖਸੁ ਦੁਸਟੁ ਹਰਿ ਮਾਰਿਆ; ", answer: "ਪ੍ਰਹਲਾਦੁ", suffix: " ਤਰਾਇਆ॥", distractors: ["ਪ੍ਰਕਾਸ", "ਬ੍ਰਹਮਾ", "ਬੀਚਾਰੇ"], bani: "Rehras Sahib" },
  { prefix: "ਅਹੰਕਾਰੀਆ ਨਿੰਦਕਾ. ਪਿਠਿ ਦੇਇ; ", answer: "ਨਾਮਦੇਉ", suffix: ". ਮੁਖਿ ਲਾਇਆ॥", distractors: ["ਆਪੀਨੑੈ", "ਹੰਢਿ॥੫", "ਹੋਈਐ"], bani: "Rehras Sahib" },
  { prefix: "ਜਨ ", answer: "ਨਾਨਕ", suffix: ". ਐਸਾ ਹਰਿ ਸੇਵਿਆ; ਅੰਤਿ ਲਏ ਛਡਾਇਆ॥੪॥੧੩॥੨੦॥", distractors: ["ਆਸਨ", "ਨਿਰਤੇ", "ਸਿਮਰਿ"], bani: "Rehras Sahib" },
  { prefix: "ਬਲਿਹਾਰੀ ", answer: "ਕੁਦਰਤਿ", suffix: " ਵਸਿਆ॥", distractors: ["ਕੀਨੇ", "ਦਰਵੇਸੀ", "ਜਾਨਾ"], bani: "Rehras Sahib" },
  { prefix: "ਤੇਰਾ ", answer: "ਅੰਤੁ", suffix: ". ਨ ਜਾਈ ਲਖਿਆ॥੧॥ਰਹਾਉ॥", distractors: ["ਮਰਣੁ", "ਪਾਲਿ", "ਕਿਹ"], bani: "Rehras Sahib" },
  { prefix: "ਸੋਦਰੁ ਰਾਗੁ ", answer: "ਆਸਾ", suffix: " ਮਹਲਾ ੧", distractors: ["ਗੁਰੁ", "ਤਾਣੁ", "ਭਗਤ"], bani: "Rehras Sahib" },
  { prefix: "ਵਾਜੇ ਤੇਰੇ ", answer: "ਨਾਦ", suffix: " ਅਨੇਕ ਅਸੰਖਾ; ਕੇਤੇ ਤੇਰੇ ਵਾਵਣਹਾਰੇ॥", distractors: ["ਏਤੇ", "ਬਾਦ", "ਰਾਮਿ"], bani: "Rehras Sahib" },
  { prefix: "ਕੇਤੇ ", answer: "ਤੇਰੇ", suffix: " ਰਾਗ ਪਰੀ ਸਿਉ ਕਹੀਅਹਿ; ਕੇਤੇ ਤੇਰੇ ਗਾਵਣਹਾਰੇ॥", distractors: ["ਆਪਿ", "ਵਾਰ॥੧", "ਮਹਿਮਾ"], bani: "Rehras Sahib" },
  { prefix: "ਗਾਵਨਿ ", answer: "ਤੁਧਨੋ", suffix: " ਪਵਣੁ ਪਾਣੀ ਬੈਸੰਤਰੁ; ਗਾਵੈ ਰਾਜਾਧਰਮੁ ਦੁਆਰੇ॥", distractors: ["ਏਤੇ", "ਸਾਚੇ", "ਹੋਈ"], bani: "Rehras Sahib" },
  { prefix: "ਗਾਵਨਿ ਤੁਧਨੋ ", answer: "ਈਸਰੁ", suffix: " ਬ੍ਰਹਮਾ ਦੇਵੀ; ਸੋਹਨਿ ਤੇਰੇ ਸਦਾ ਸਵਾਰੇ॥", distractors: ["ਕੰਚਨੁ", "ਨਿੰਦਕਾ", "ਬਾਤਾ"], bani: "Rehras Sahib" },
  { prefix: "ਸੋਹਿਲਾ ਰਾਗੁ ਗਉੜੀ ਦੀਪਕੀ ", answer: "ਮਹਲਾ", suffix: " ੧", distractors: ["ਚਲਾਂ", "ਨਿਧਾਨੁ", "ਆਵੈ"], bani: "Kirtan Sohila" },
  { prefix: "ਜੈ ਘਰਿ ", answer: "ਕੀਰਤਿ", suffix: " ਆਖੀਐ; ਕਰਤੇ ਕਾ ਹੋਇ ਬੀਚਾਰੋ॥", distractors: ["ਦੇਖਿ", "ਅਗਨਤ", "ਧਰਹੁ"], bani: "Kirtan Sohila" },
  { prefix: "ਤਿਤੁ ਘਰਿ ਗਾਵਹੁ ", answer: "ਸੋਹਿਲਾ", suffix: "; ਸਿਵਰਿਹੁ ਸਿਰਜਣਹਾਰੋ॥੧॥", distractors: ["ਮੁਹਾਇ॥੧", "ਧੰਨਾ॥੧", "ਭੰਜਨੁ"], bani: "Kirtan Sohila" },
  { prefix: "ਤੁਮ ਗਾਵਹੁ; ਮੇਰੇ ", answer: "ਨਿਰਭਉ", suffix: " ਕਾ ਸੋਹਿਲਾ॥", distractors: ["ਸਮਰਥੁ", "ਸੁਖਮਨੀ", "ਭਾਹਿ"], bani: "Kirtan Sohila" },
  { prefix: "ਹਉ ਵਾਰੀ; ਜਿਤੁ ਸੋਹਿਲੈ ", answer: "ਸਦਾ", suffix: " ਸੁਖੁ ਹੋਇ॥੧॥ਰਹਾਉ॥", distractors: ["ਕੰਚਨ", "ਘਨੇਰੇ", "ਤੇਰੇ"], bani: "Kirtan Sohila" },
  { prefix: "ਨਿਤ ਨਿਤ ", answer: "ਜੀਅੜੇ", suffix: " ਸਮਾਲੀਅਨਿ; ਦੇਖੈਗਾ ਦੇਵਣਹਾਰੁ॥", distractors: ["ਆਪਿ", "ਮਾਇਓ", "ਸਰਬ"], bani: "Kirtan Sohila" },
  { prefix: "ਤੇਰੇ ਦਾਨੈ ਕੀਮਤਿ ਨਾ ਪਵੈ; ਤਿਸੁ ", answer: "ਦਾਤੇ", suffix: " ਕਵਣੁ ਸੁਮਾਰੁ॥੨॥", distractors: ["ਆਸਨ", "ਸੁਹਾਵਾ", "ਤੂੰ"], bani: "Kirtan Sohila" },
  { prefix: "ਸੰਬਤਿ ", answer: "ਸਾਹਾ", suffix: " ਲਿਖਿਆ; ਮਿਲਿ ਕਰਿ ਪਾਵਹੁ ਤੇਲੁ॥", distractors: ["ਆਪਿ", "ਰਛਾ", "ਫਿਰਿਓ"], bani: "Kirtan Sohila" },
  { prefix: "ਦੇਹੁ ਸਜਣ ਅਸੀਸੜੀਆ; ਜਿਉ ਹੋਵੈ ", answer: "ਸਾਹਿਬ", suffix: " ਸਿਉ ਮੇਲੁ॥੩॥", distractors: ["ਹੋਦਿਆਂ", "ਬੀਚਾਰੇ", "ਕੀਨੇ"], bani: "Kirtan Sohila" },
  { prefix: "ਘਰਿ ", answer: "ਘਰਿ", suffix: " ਏਹੁ ਪਾਹੁਚਾ; ਸਦੜੇ ਨਿਤ ਪਵੰਨਿ॥", distractors: ["ਮਿਲੈ", "ਓਟਿ", "ਗੋਪਾਲ"], bani: "Kirtan Sohila" },
  { prefix: "ਸਦਣਹਾਰਾ ", answer: "ਸਿਮਰੀਐ", suffix: "; ਨਾਨਕ. ਸੇ ਦਿਹ ਆਵੰਨਿ॥੪॥੧॥", distractors: ["ਸੁਣੀਆਇ", "ਉਤਮੁ", "ਤੁਰੀ"], bani: "Kirtan Sohila" },
  { prefix: "ਛਿਅ ਘਰ, ਛਿਅ ", answer: "ਗੁਰ", suffix: "; ਛਿਅ ਉਪਦੇਸ॥", distractors: ["ਕਾਲੁ", "ਲਿਖਿ", "ਜਿਤੁ"], bani: "Kirtan Sohila" },
  { prefix: "ਗੁਰੁ ਗੁਰੁ ਏਕੋ; ", answer: "ਵੇਸ", suffix: " ਅਨੇਕ॥੧॥", distractors: ["ਵਾਰ", "ਆਪਨਾ", "ਸਭਸੈ"], bani: "Kirtan Sohila" },
  { prefix: "ਬਾਬਾ, ਜੈ ", answer: "ਘਰਿ", suffix: "; ਕਰਤੇ ਕੀਰਤਿ ਹੋਇ॥", distractors: ["ਪੁਰਖ", "ਸਿਮਰਿ", "ਵਡਿਆਈ"], bani: "Kirtan Sohila" },
  { prefix: "ਸੋ ਘਰੁ ਰਾਖੁ; ", answer: "ਵਡਾਈ", suffix: " ਤੋਇ॥੧॥ਰਹਾਉ॥", distractors: ["ਭਿੰਨੇ", "ਤੇਰੀ", "ਜਾਸੁ"], bani: "Kirtan Sohila" },
  { prefix: "ਵਿਸੁਏ ਚਸਿਆ ", answer: "ਘੜੀਆ", suffix: " ਪਹਰਾ; ਥਿਤੀ ਵਾਰੀ ਮਾਹੁ ਹੋਆ॥", distractors: ["ਸਚੁ॥੧", "ਸਾਹਿਬ", "ਤੇਰਾ"], bani: "Kirtan Sohila" },
  { prefix: "ਸੂਰਜੁ ", answer: "ਏਕੋ", suffix: "; ਰੁਤਿ ਅਨੇਕ॥", distractors: ["ਜੋਲਿ", "ਪਹਿ", "ਕੀਆ"], bani: "Kirtan Sohila" },
  { prefix: "ਨਾਨਕ; ਕਰਤੇ ਕੇ ", answer: "ਕੇਤੇ", suffix: " ਵੇਸ॥੨॥੨॥", distractors: ["ਪੀਡੀ", "ਤੇਰੇ", "ਸੂਖ"], bani: "Kirtan Sohila" },
  { prefix: "ਗੁਰਦੇਵ ", answer: "ਮਾਤਾ", suffix: ". ਗੁਰਦੇਵ ਪਿਤਾ; ਗੁਰਦੇਵ ਸੁਆਮੀ ਪਰਮੇਸੁਰਾ॥", distractors: ["ਅਧਾਰੁ", "ਪੀਡੀ", "ਲਾਲ"], bani: "Bavan Akhri" },
  { prefix: "ਗੁਰਦੇਵ ਸਖਾ. ਅਗਿਆਨ ਭੰਜਨੁ; ਗੁਰਦੇਵ ", answer: "ਬੰਧਿਪ", suffix: " ਸਹੋਦਰਾ॥", distractors: ["ਕਛੁ", "ਇਕਿ", "ਬੂਆੜ"], bani: "Bavan Akhri" },
  { prefix: "ਗੁਰਦੇਵ ਦਾਤਾ. ", answer: "ਹਰਿ", suffix: " ਨਾਮੁ ਉਪਦੇਸੈ; ਗੁਰਦੇਵ ਮੰਤੁ. ਨਿਰੋਧਰਾ॥", distractors: ["ਮਾਹੇ", "ਜੋਤਿ", "ਕੀਆ"], bani: "Bavan Akhri" },
  { prefix: "ਗੁਰਦੇਵ ਸਾਂਤਿ ਸਤਿ ", answer: "ਬੁਧਿ", suffix: " ਮੂਰਤਿ; ਗੁਰਦੇਵ. ਪਾਰਸ ਪਰਸ ਪਰਾ॥", distractors: ["ਈਸਰੁ", "ਜਪਿ", "ਧਰਮੁ"], bani: "Bavan Akhri" },
  { prefix: "ਗੁਰਦੇਵ ਤੀਰਥੁ ਅੰਮ੍ਰਿਤ ", answer: "ਸਰੋਵਰੁ", suffix: "; ਗੁਰ ਗਿਆਨ ਮਜਨੁ ਅਪਰੰਪਰਾ॥", distractors: ["ਚਲਣਾ", "ਮਾਨੈ", "ਸਮਝਾਇ"], bani: "Bavan Akhri" },
  { prefix: "ਗੁਰਦੇਵ ਕਰਤਾ. ਸਭਿ ਪਾਪ ਹਰਤਾ; ਗੁਰਦੇਵ, ", answer: "ਪਤਿਤ", suffix: " ਪਵਿਤ ਕਰਾ॥", distractors: ["ਤਾਮਿ", "ਰੰਗ", "ਹੋਹਿ"], bani: "Bavan Akhri" },
  { prefix: "ਗੁਰਦੇਵ ਸਤਿਗੁਰੁ ਪਾਰਬ੍ਰਹਮੁ ਪਰਮੇਸਰੁ; ਗੁਰਦੇਵ ਨਾਨਕ ", answer: "ਹਰਿ", suffix: " ਨਮਸਕਰਾ॥੧॥", distractors: ["ਰਖਦਾ", "ਅਧਾਰੁ", "ਸੁਣਹੁ"], bani: "Bavan Akhri" },
  { prefix: "ਆਪਹਿ ਕੀਆ ਕਰਾਇਆ; ", answer: "ਆਪਹਿ", suffix: " ਕਰਨੈ ਜੋਗੁ॥", distractors: ["ਸਕਤਿ", "ਕਰੀ", "ਕਿਝੁ"], bani: "Bavan Akhri" },
  { prefix: "ਨਾਨਕ. ਏਕੋ ਰਵਿ ", answer: "ਰਹਿਆ", suffix: "; ਦੂਸਰ. ਹੋਆ ਨ ਹੋਗੁ॥੧॥", distractors: ["ਕਸਵਟੀ", "ਕਰੇ", "ਸੁਣੀਦਾ"], bani: "Bavan Akhri" },
  { prefix: "ਓਅੰ ", answer: "ਸਾਧ", suffix: " ਸਤਿਗੁਰ; ਨਮਸਕਾਰੰ॥", distractors: ["ਡਿਠੋ", "ਤਾਨ", "ਸਕਤਿ"], bani: "Bavan Akhri" },
  { prefix: "ਆਦਿ ", answer: "ਮਧਿ", suffix: " ਅੰਤਿ; ਨਿਰੰਕਾਰੰ॥", distractors: ["ਹੋਇ", "ਧਾਇ", "ਚਾਖੀਐ"], bani: "Bavan Akhri" },
  { prefix: "ਆਪਹਿ ਸੁੰਨ; ਆਪਹਿ ", answer: "ਸੁਖ", suffix: " ਆਸਨ॥", distractors: ["ਸਵਾਰਿ", "ਜੋਗੁ", "ਮਾਹੁ"], bani: "Bavan Akhri" },
  { prefix: "ਆਪਹਿ ", answer: "ਸੁਨਤ", suffix: "; ਆਪ ਹੀ ਜਾਸਨ॥", distractors: ["ਜਾਣੈ", "ਆਪਿ॥੩", "ਕਢੀਐ"], bani: "Bavan Akhri" },
  { prefix: "ਆਪਨਿ ਆਪੁ; ", answer: "ਆਪਹਿ", suffix: " ਉਪਾਇਓ॥", distractors: ["ਜੁਗਾਦਿ", "ਆਪਣੈ", "ਅਗਮ"], bani: "Bavan Akhri" },
  { prefix: "ਆਪਹਿ ", answer: "ਬਾਪ", suffix: "; ਆਪ ਹੀ ਮਾਇਓ॥", distractors: ["ਕਿਹ", "ਸਹੁ", "ਜੇਵਡੁ"], bani: "Bavan Akhri" },
  { prefix: "ਆਪਹਿ ", answer: "ਸੂਖਮ", suffix: "; ਆਪਹਿ ਅਸਥੂਲਾ॥", distractors: ["ਸੁਣਹੁ", "ਪਾਤਾ", "ਮਾਰਿਆ"], bani: "Bavan Akhri" },
  { prefix: "ਹਰਿ ਅੰਮ੍ਰਿਤ ਭਿੰਨੇ ਲੋਇਣਾ; ਮਨੁ ਪ੍ਰੇਮਿ ", answer: "ਰਤੰਨਾ", suffix: " ਰਾਮ ਰਾਜੇ॥", distractors: ["ਨਿਰਭਉ", "ਭੁਖਾ", "ਅਦ੍ਵੈ"], bani: "Asa Di Vaar" },
  { prefix: "ਮਨੁ. ", answer: "ਰਾਮਿ", suffix: " ਕਸਵਟੀ ਲਾਇਆ; ਕੰਚਨੁ ਸੋਵਿੰਨਾ॥", distractors: ["ਉਪਦੇਸ", "ਸਰਬ", "ਕੀਨੇ"], bani: "Asa Di Vaar" },
  { prefix: "ਗੁਰਮੁਖਿ ਰੰਗਿ ਚਲੂਲਿਆ; ਮੇਰਾ ਮਨੁ ", answer: "ਤਨੋ", suffix: " ਭਿੰਨਾ॥", distractors: ["ਆਧੁ", "ਨਿਰਭਉ", "ਵਡਾਈ"], bani: "Asa Di Vaar" },
  { prefix: "ਜਨੁ ਨਾਨਕੁ. ਮੁਸਕਿ ਝਕੋਲਿਆ; ਸਭੁ ", answer: "ਜਨਮੁ", suffix: " ਧਨੁ ਧੰਨਾ॥੧॥", distractors: ["ਕੀਤੀ", "ਪਸਾਉ", "ਕਾਰਜ"], bani: "Asa Di Vaar" },
  { prefix: "ਬਲਿਹਾਰੀ ", answer: "ਗੁਰ", suffix: " ਆਪਣੇ; ਦਿਉਹਾੜੀ ਸਦ ਵਾਰ॥", distractors: ["ਦਾਤਾ", "ਨਿਆਰਾ", "ਆਪਨਾ"], bani: "Asa Di Vaar" },
  { prefix: "ਜਿਨਿ. ਮਾਣਸ ਤੇ ਦੇਵਤੇ ", answer: "ਕੀਏ", suffix: "; ਕਰਤ. ਨ ਲਾਗੀ ਵਾਰ॥੧॥", distractors: ["ਚੜਹਿ", "ਸੋਇ॥੭", "ਜਿਨੀ"], bani: "Asa Di Vaar" },
  { prefix: "ਜੇ. ਸਉ ", answer: "ਚੰਦਾ", suffix: " ਉਗਵਹਿ; ਸੂਰਜ ਚੜਹਿ ਹਜਾਰ॥", distractors: ["ਦੂਖ", "ਸੱਤ੍ਰ", "ਮਿੱਤ੍ਰ"], bani: "Asa Di Vaar" },
  { prefix: "ਏਤੇ ਚਾਨਣ ਹੋਦਿਆਂ; ਗੁਰ ", answer: "ਬਿਨੁ", suffix: ". ਘੋਰ ਅੰਧਾਰ॥੨॥", distractors: ["ਲਾਗੈ", "ਸੁੰਨ", "ਕੂੜੈ"], bani: "Asa Di Vaar" },
  { prefix: "ਨਾਨਕ. ਗੁਰੂ ਨ ", answer: "ਚੇਤਨੀ", suffix: "; ਮਨਿ ਆਪਣੈ ਸੁਚੇਤ॥", distractors: ["ਕੁਰਬਾਣੁ", "ਸੂਖ", "ਸੋਚਿ"], bani: "Asa Di Vaar" },
  { prefix: "ਛੁਟੇ ਤਿਲ ", answer: "ਬੂਆੜ", suffix: " ਜਿਉ; ਸੁੰਞੇ ਅੰਦਰਿ ਖੇਤ॥", distractors: ["ਨੇਤ", "ਅਮਿਤੋਜ", "ਗਲਿ"], bani: "Asa Di Vaar" },
  { prefix: "ਖੇਤੈ ਅੰਦਰਿ ਛੁਟਿਆ; ", answer: "ਕਹੁ", suffix: " ਨਾਨਕ. ਸਉ ਨਾਹ॥", distractors: ["ਪਾਵਹੁ", "ਸੁਰ", "ਜਿਨਿ"], bani: "Asa Di Vaar" },
  { prefix: "ਫਲੀਅਹਿ ਫੁਲੀਅਹਿ ", answer: "ਬਪੁੜੇ", suffix: "; ਭੀ. ਤਨ ਵਿਚਿ ਸੁਆਹ॥੩॥", distractors: ["ਕੀਮਤਿ", "ਸੁਣਹੁ", "ਵੇਸ"], bani: "Asa Di Vaar" },
  { prefix: "ਆਪੀਨੑੈ ", answer: "ਆਪੁ", suffix: " ਸਾਜਿਓ; ਆਪੀਨੑੈ ਰਚਿਓ ਨਾਉ॥", distractors: ["ਪਰਣਾਇ", "ਆਪਣੈ", "ਭਾਰ"], bani: "Asa Di Vaar" },
  { prefix: "ਦੁਯੀ. ਕੁਦਰਤਿ ", answer: "ਸਾਜੀਐ", suffix: "; ਕਰਿ ਆਸਣੁ ਡਿਠੋ ਚਾਉ॥", distractors: ["ਗੀਤ", "ਸੋਹਿਲਾ", "ਪਹਿ"], bani: "Asa Di Vaar" },
  { prefix: "ਦਾਤਾ ਕਰਤਾ. ਆਪਿ ", answer: "ਤੂੰ", suffix: "; ਤੁਸਿ ਦੇਵਹਿ. ਕਰਹਿ ਪਸਾਉ॥", distractors: ["ਦਯੁ", "ਜਪਿ", "ਜਤੀ"], bani: "Asa Di Vaar" },
  { prefix: "ਤੂੰ ", answer: "ਜਾਣੋਈ", suffix: " ਸਭਸੈ; ਦੇ ਲੈਸਹਿ. ਜਿੰਦੁ ਕਵਾਉ॥", distractors: ["ਲਾਗੈ", "ਗਾਉ॥੧", "ਨਮੋ"], bani: "Asa Di Vaar" },
  { prefix: "ਕਰਿ ਆਸਣੁ; ", answer: "ਡਿਠੋ", suffix: " ਚਾਉ॥੧॥", distractors: ["ਜੁਗਾਦੀ", "ਉਗਵਹਿ", "ਸੰਗੀ"], bani: "Asa Di Vaar" },
  { prefix: "ਹਰਿ ਪ੍ਰੇਮ ਬਾਣੀ. ", answer: "ਮਨੁ", suffix: " ਮਾਰਿਆ; ਅਣੀਆਲੇ ਅਣੀਆ. ਰਾਮ ਰਾਜੇ॥", distractors: ["ਨਹਿਨ", "ਸਾਖੀਐ", "ਮੀਤੁ"], bani: "Asa Di Vaar" },
  { prefix: "ਦੁਖ ਭੰਜਨੁ. ਤੇਰਾ ਨਾਮੁ ਜੀ; ", answer: "ਦੁਖ", suffix: " ਭੰਜਨੁ. ਤੇਰਾ ਨਾਮੁ॥", distractors: ["ਸੇਵਾ", "ਰਸਨਾ", "ਦੂਸਰ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਆਠ ", answer: "ਪਹਰ", suffix: " ਆਰਾਧੀਐ; ਪੂਰਨ ਸਤਿਗੁਰ ਗਿਆਨੁ॥੧॥ਰਹਾਉ॥", distractors: ["ਕਾਨ", "ਜੁਗੁ", "ਗੁਝੀ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਜਿਤੁ ਘਟਿ ਵਸੈ ਪਾਰਬ੍ਰਹਮੁ; ਸੋਈ ", answer: "ਸੁਹਾਵਾ", suffix: " ਥਾਉ॥", distractors: ["ਦੁਨੀਆਂ", "ਅੰਮ੍ਰਿਤ", "ਕੀਨੇ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਜਮਕੰਕਰੁ. ਨੇੜਿ ਨ ਆਵਈ; ਰਸਨਾ ਹਰਿ ", answer: "ਗੁਣ", suffix: " ਗਾਉ॥੧॥", distractors: ["ਬਪੁੜੇ", "ਨਚਤੁ", "ਦਾਲਿ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਸੇਵਾ ਸੁਰਤਿ. ਨ ", answer: "ਜਾਣੀਆ", suffix: "; ਨਾ ਜਾਪੈ ਆਰਾਧਿ॥", distractors: ["ਮੂਰਤਿ", "ਬਰਨਤ", "ਕਰੇ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਓਟਿ ਤੇਰੀ ਜਗਜੀਵਨਾ; ਮੇਰੇ ", answer: "ਠਾਕੁਰ", suffix: " ਅਗਮ ਅਗਾਧਿ॥੨॥", distractors: ["ਮਹਿਮਾ", "ਗਲਿ", "ਜਨਮੁ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਭਏ ", answer: "ਕ੍ਰਿਪਾਲ", suffix: " ਗੁਸਾਈਆ; ਨਠੇ ਸੋਗ ਸੰਤਾਪ॥", distractors: ["ਭੰਜਨੁ", "ਅਕਾਲਪੁਰਖ", "ਵਿਖਮੁ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਤਤੀ ਵਾਉ. ਨ ", answer: "ਲਗਈ", suffix: "; ਸਤਿਗੁਰਿ ਰਖੇ ਆਪਿ॥੩॥", distractors: ["ਨਾਹਿ", "ਫਰੀਦਾ", "ਉਪਾਇਓ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਗੁਰੁ ਨਾਰਾਇਣੁ. ਦਯੁ ", answer: "ਗੁਰੁ", suffix: "; ਗੁਰੁ ਸਚਾ ਸਿਰਜਣਹਾਰੁ॥", distractors: ["ਲਿਖਾਇ", "ਤੇਰਾ", "ਸਕਤਿ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਗੁਰਿ ", answer: "ਤੁਠੈ", suffix: ". ਸਭ ਕਿਛੁ ਪਾਇਆ; ਜਨ ਨਾਨਕ. ਸਦ ਬਲਿਹਾਰ॥੪॥੨॥੧੭੦॥", distractors: ["ਸਿਆਣਪਾ", "ਤਾਤ", "ਬੰਨਾ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਕੀਤਾ ਲੋੜੀਐ ਕੰਮੁ; ਸੁ ", answer: "ਹਰਿ", suffix: " ਪਹਿ ਆਖੀਐ॥", distractors: ["ਸੁਝੈ", "ਪਾਰਿ", "ਦੁਨੀਆ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਕਾਰਜੁ ਦੇਇ ਸਵਾਰਿ; ਸਤਿਗੁਰ ", answer: "ਸਚੁ", suffix: " ਸਾਖੀਐ॥", distractors: ["ਸੰਤਾਪ", "ਤੇਰੀ", "ਰੁਤਿ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਸੰਤਾ ", answer: "ਸੰਗਿ", suffix: " ਨਿਧਾਨੁ; ਅੰਮ੍ਰਿਤੁ ਚਾਖੀਐ॥", distractors: ["ਗੁਣ", "ਪਰਣਾਇ", "ਸਕਤਿ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਭੈ ਭੰਜਨ ", answer: "ਮਿਹਰਵਾਨ", suffix: "; ਦਾਸ ਕੀ ਰਾਖੀਐ॥", distractors: ["ਸੱਤ੍ਰ", "ਚੰਗੇਰੀ", "ਸਿੱਧੇ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਨਾਨਕ. ਹਰਿ ਗੁਣ ਗਾਇ; ਅਲਖੁ ", answer: "ਪ੍ਰਭੁ", suffix: " ਲਾਖੀਐ॥੨੦॥", distractors: ["ਜੜਾਉ", "ਨਾਦ", "ਭਤਿ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਸੂਕੇ ", answer: "ਹਰੇ", suffix: " ਕੀਏ; ਖਿਨ ਮਾਹੇ॥", distractors: ["ਥੋੜੜੇ", "ਤੀਰਥੁ", "ਚੇਤਨੀ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਅੰਮ੍ਰਿਤ ਦ੍ਰਿਸਟਿ ", answer: "ਸੰਚਿ", suffix: "; ਜੀਵਾਏ॥੧॥", distractors: ["ਹਮਾਰਾ", "ਮੰਤੁ", "ਰਾਵ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਕਾਟੇ ਕਸਟ; ", answer: "ਪੂਰੇ", suffix: " ਗੁਰਦੇਵ॥", distractors: ["ਪੂਰਨ", "ਪਾਤਾ", "ਸਦੜੇ"], bani: "Dukh Bhanjani Sahib" },
  { prefix: "ਕਬੀਰ. ਮੇਰੀ ", answer: "ਸਿਮਰਨੀ", suffix: "; ਰਸਨਾ ਊਪਰਿ ਰਾਮੁ॥", distractors: ["ਵਸਾਵਏ", "ਰਸਨਾ", "ਚੇਤਨੀ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਆਦਿ ", answer: "ਜੁਗਾਦੀ", suffix: " ਸਗਲ ਭਗਤ; ਤਾ ਕੋ ਸੁਖੁ ਬਿਸ੍ਰਾਮੁ॥੧॥", distractors: ["ਧੰਨਾ", "ਵਾਰ॥੧", "ਹਉਮੈ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ਮੇਰੀ ਜਾਤਿ ਕਉ; ", answer: "ਸਭੁ", suffix: " ਕੋ ਹਸਨੇਹਾਰੁ॥", distractors: ["ਦੇਵਤੇ", "ਕਰਾ", "ਜਾਣੈ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਬਲਿਹਾਰੀ ਇਸ ਜਾਤਿ ਕਉ; ਜਿਹ ", answer: "ਜਪਿਓ", suffix: " ਸਿਰਜਨਹਾਰੁ॥੨॥", distractors: ["ਤੁਰੀ", "ਚੁਪੈ", "ਹੋਸੀ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ਡਗਮਗ ", answer: "ਕਿਆ", suffix: " ਕਰਹਿ; ਕਹਾ ਡੁਲਾਵਹਿ ਜੀਉ॥", distractors: ["ਕੈਸੇ", "ਅਸੰਖਾ", "ਆਪੁ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਸਰਬ ਸੂਖ ਕੋ ", answer: "ਨਾਇਕੋ", suffix: "; ਰਾਮ ਨਾਮ ਰਸੁ ਪੀਉ॥੩॥", distractors: ["ਪਾਵਉ", "ਮੇਰੇ", "ਹੋਈ॥੧"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ", answer: "ਕੰਚਨ", suffix: " ਕੇ ਕੁੰਡਲ ਬਨੇ; ਊਪਰਿ ਲਾਲ ਜੜਾਉ॥", distractors: ["ਪਿਤਾ", "ਨੰਢੜਾ", "ਲੇਖੁ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਦੀਸਹਿ. ਦਾਧੇ ਕਾਨ ਜਿਉ; ਜਿਨੑ ", answer: "ਮਨਿ", suffix: ". ਨਾਹੀ ਨਾਉ॥੪॥", distractors: ["ਘ੍ਰਿਤ", "ਹੋਈ", "ਸੰਤਾਪ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ਐਸਾ ਏਕੁ ਆਧੁ; ਜੋ ", answer: "ਜੀਵਤ", suffix: " ਮਿਰਤਕੁ ਹੋਇ॥", distractors: ["ਬੀਚ", "ਨਿਧਾਨੁ", "ਜਪਤ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਨਿਰਭੈ ਹੋਇ ਕੈ ", answer: "ਗੁਨ", suffix: " ਰਵੈ; ਜਤ ਪੇਖਉ ਤਤ ਸੋਇ॥੫॥", distractors: ["ਸਿਮਰਉ", "ਸੋਦਰੁ", "ਅਚਲ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ਜਾ ", answer: "ਦਿਨ", suffix: " ਹਉ ਮੂਆ; ਪਾਛੈ ਭਇਆ ਅਨੰਦੁ॥", distractors: ["ਪੈਜ", "ਛਿਜਣਾ", "ਗੀਤੇ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਮੋਹਿ. ਮਿਲਿਓ ਪ੍ਰਭੁ ਆਪਨਾ; ਸੰਗੀ ", answer: "ਭਜਹਿ", suffix: " ਗੋੁਬਿੰਦੁ॥੬॥", distractors: ["ਪੁਰੀਆ", "ਆਪਿ", "ਮਿਲਿ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਜਿਨਿ ਐਸਾ ", answer: "ਕਰਿ", suffix: " ਬੂਝਿਆ; ਮੀਤੁ ਹਮਾਰਾ ਸੋਇ॥੭॥", distractors: ["ਕਿਉ", "ਬੂਝਿਆ", "ਕੀਓ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ਆਈ ਮੁਝਹਿ ਪਹਿ; ਅਨਿਕ ", answer: "ਕਰੇ", suffix: " ਕਰਿ ਭੇਸ॥", distractors: ["ਸੁਧ", "ਰਛਾ", "ਰੰਗਿ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਹਮ ਰਾਖੇ. ਗੁਰ ਆਪਨੇ; ਉਨਿ ", answer: "ਕੀਨੋ", suffix: " ਆਦੇਸੁ॥੮॥", distractors: ["ਤੇਰੈ", "ਸੇਤੀ", "ਪਾਨ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਕਬੀਰ. ਸੋਈ ਮਾਰੀਐ; ਜਿਹ ਮੂਐ ", answer: "ਸੁਖੁ", suffix: " ਹੋਇ॥", distractors: ["ਸਾਹਿਬੁ", "ਬੂਝਿਆ", "ਪਵਣੁ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਭਲੋ ਭਲੋ ਸਭੁ ਕੋ ਕਹੈ; ਬੁਰੋ. ਨ ", answer: "ਮਾਨੈ", suffix: " ਕੋਇ॥੯॥", distractors: ["ਪਾਪ", "ਕੇਹਾ", "ਸੁਧ"], bani: "Salok Bhagat Kabir" },
  { prefix: "ਜਿਤੁ ਦਿਹਾੜੈ. ਧਨ ", answer: "ਵਰੀ", suffix: "; ਸਾਹੇ ਲਏ ਲਿਖਾਇ॥", distractors: ["ਬਿਨੁ", "ਜੀਉ", "ਜਿਤੁ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਮਲਕੁ. ਜਿ ਕੰਨੀ ਸੁਣੀਦਾ; ", answer: "ਮੁਹੁ", suffix: " ਦੇਖਾਲੇ ਆਇ॥", distractors: ["ਸੋਹਨਿ", "ਸੰਬਤਿ", "ਭਾਹਿ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਜਿੰਦੁ ਨਿਮਾਣੀ ", answer: "ਕਢੀਐ", suffix: "; ਹਡਾ ਕੂ ਕੜਕਾਇ॥", distractors: ["ਲਿਖੁ", "ਜਤੀ", "ਜੀਉ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਸਾਹੇ ਲਿਖੇ. ਨ ਚਲਨੀ; ਜਿੰਦੂ ", answer: "ਕੂੰ", suffix: " ਸਮਝਾਇ॥", distractors: ["ਏਹੁ", "ਹੁਕਮੀ", "ਤੀਰਥੁ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਜਿੰਦੁ ਵਹੁਟੀ. ", answer: "ਮਰਣੁ", suffix: " ਵਰੁ; ਲੈ ਜਾਸੀ ਪਰਣਾਇ॥", distractors: ["ਜਿੰਦੁ", "ਦਾਨੈ", "ਤੇਲੁ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਆਪਣ ", answer: "ਹਥੀ", suffix: ". ਜੋਲਿ ਕੈ; ਕੈ ਗਲਿ ਲਗੈ ਧਾਇ॥", distractors: ["ਕੀਨੇ", "ਕੋਇ॥੯", "ਜਾਈ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਵਾਲਹੁ ਨਿਕੀ ਪੁਰ ਸਲਾਤ; ", answer: "ਕੰਨੀ", suffix: ". ਨ ਸੁਣੀਆਇ॥", distractors: ["ਸਲਾਤ", "ਕੁਦਰਤਿ", "ਸਾਚਾ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਫਰੀਦਾ. ਕਿੜੀ ", answer: "ਪਵੰਦੀਈ", suffix: "; ਖੜਾ. ਨ ਆਪੁ ਮੁਹਾਇ॥੧॥", distractors: ["ਇੰਦ੍ਰਾਣਿ", "ਭਵਾਈਅਹਿ", "ਬ੍ਰਹਮਾ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਫਰੀਦਾ. ਦਰ ਦਰਵੇਸੀ ਗਾਖੜੀ; ", answer: "ਚਲਾਂ", suffix: " ਦੁਨੀਆਂ ਭਤਿ॥", distractors: ["ਮਹੀਪ", "ਪੇਖਉ", "ਪਇਆ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਬੰਨਿੑ ", answer: "ਉਠਾਈ", suffix: " ਪੋਟਲੀ; ਕਿਥੈ ਵੰਞਾ ਘਤਿ॥੨॥", distractors: ["ਘੀਉ", "ਪਰਮ", "ਨਾਮੁ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਕਿਝੁ. ਨ ਬੁਝੈ, ਕਿਝੁ. ਨ ਸੁਝੈ; ਦੁਨੀਆ ", answer: "ਗੁਝੀ", suffix: " ਭਾਹਿ॥", distractors: ["ਸਵਾਰਣਾ", "ਅਬਗਤ", "ਸੋਦਰੁ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਫਰੀਦਾ. ਜੇ ਜਾਣਾ ਤਿਲ ਥੋੜੜੇ; ਸੰਮਲਿ ", answer: "ਬੁਕੁ", suffix: " ਭਰੀ॥", distractors: ["ਨਹਿਨ", "ਫਿਰਿਓ", "ਅਣੀਆ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਜੇ ਜਾਣਾ ਸਹੁ ", answer: "ਨੰਢੜਾ", suffix: "; ਤਾਂ. ਥੋੜਾ ਮਾਣੁ ਕਰੀ॥੪॥", distractors: ["ਜੋਗੁ", "ਸਾਚੇ", "ਧਰਮੁ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਜੇ ਜਾਣਾ ਲੜੁ ਛਿਜਣਾ; ", answer: "ਪੀਡੀ", suffix: " ਪਾਈਂ ਗੰਢਿ॥", distractors: ["ਮਹਲਾ", "ਸੁਹਾਵਾ", "ਸੁਆਹ॥੩"], bani: "Salok Bhagat Farid" },
  { prefix: "ਤੈ ਜੇਵਡੁ. ਮੈ ਨਾਹਿ ਕੋ; ਸਭੁ ਜਗੁ ", answer: "ਡਿਠਾ", suffix: " ਹੰਢਿ॥੫॥", distractors: ["ਹੋਈਐ", "ਰਾਮਾ", "ਚਾਨਣ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਫਰੀਦਾ. ਜੇ ਤੂ ਅਕਲਿ ਲਤੀਫੁ; ਕਾਲੇ ", answer: "ਲਿਖੁ", suffix: ". ਨ ਲੇਖੁ॥", distractors: ["ਚਾਖੀਐ", "ਜਿੰਦੂ", "ਪਾਇਆ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਆਪਨੜੇ ਗਿਰੀਵਾਨ ਮਹਿ; ਸਿਰੁ ", answer: "ਨੀਂਵਾਂ", suffix: " ਕਰਿ ਦੇਖੁ॥੬॥", distractors: ["ਅਸਥੂਲਾ", "ਬਾਤਾ", "ਪਸਾਰਾ"], bani: "Salok Bhagat Farid" },
  { prefix: "ਅਕਾਲਪੁਰਖ ਕੀ; ", answer: "ਰਛਾ", suffix: " ਹਮਨੈ॥", distractors: ["ਹੋਸੀ", "ਗਲਾ", "ਭਰੀ"], bani: "Chaupai Sahib" },
  { prefix: "ਸਰਬ ", answer: "ਲੋਹ", suffix: " ਦੀ; ਰਛਿਆ ਹਮਨੈ॥", distractors: ["ਸਭੁ", "ਰਜਾਈ", "ਅੰਤੁ"], bani: "Chaupai Sahib" },
  { prefix: "ਸਰਬ ਕਾਲ ਜੀ ਦੀ; ", answer: "ਰਛਿਆ", suffix: " ਹਮਨੈ॥", distractors: ["ਰਹਿਆ", "ਮੁਝਹਿ", "ਵੰਞਾ"], bani: "Chaupai Sahib" },
  { prefix: "ਜਲ ਥਲ ", answer: "ਮਹੀਅਲ", suffix: " ਕੀਓ ਪਸਾਰਾ॥", distractors: ["ਰਾਮੁ", "ਨਿਰਭੈ", "ਕਾਨ"], bani: "Chaupai Sahib" },
  { prefix: "ਆਦਿ ਪੁਰਖ ", answer: "ਅਬਗਤ", suffix: " ਅਬਿਨਾਸੀ॥", distractors: ["ਗਾਖੜੀ", "ਆਪਿ॥੩", "ਜਾਸੁ"], bani: "Chaupai Sahib" },
  { prefix: "ਲੋਕ ਚੱਤ੍ਰੁਦਸ ", answer: "ਜੋਤਿ", suffix: " ਪ੍ਰਕਾਸੀ॥੧॥", distractors: ["ਦਰਵੇਸੀ", "ਚਲਣਾ", "ਪਿਠਿ"], bani: "Chaupai Sahib" },
  { prefix: "ਹਸਤ ਕੀਟ ਕੇ ", answer: "ਬੀਚ", suffix: " ਸਮਾਨਾ॥", distractors: ["ਦੇਵੀ", "ਪਇਆ", "ਤਾਂ"], bani: "Chaupai Sahib" },
  { prefix: "ਰਾਵ ਰੰਕ ", answer: "ਜਿਹ", suffix: " ਇਕਸਰ ਜਾਨਾ॥", distractors: ["ਜਿਸ", "ਓਹੁ", "ਭਾਰ"], bani: "Chaupai Sahib" },
  { prefix: "ਅਦ੍ਵੈ ", answer: "ਅਲਖ", suffix: " ਪੁਰਖ ਅਬਿਗਾਮੀ॥", distractors: ["ਰਹਿਆ", "ਆਸਨ", "ਨਹਿਨ"], bani: "Chaupai Sahib" },
  { prefix: "ਅਲਖ ", answer: "ਰੂਪ", suffix: " ਅੱਛੈ ਅਨਭੇਖਾ॥", distractors: ["ਸਾਹਿ", "ਉਪਾਇਆ", "ਸਾਹੇ"], bani: "Chaupai Sahib" },
  { prefix: "ਬਰਨ ", answer: "ਚਿਹਨ", suffix: " ਸਭਹੂੰ ਤੇ ਨਿਆਰਾ॥", distractors: ["ਸੂਰਜੁ", "ਅਸੰਖਾ", "ਜਾਣਨਿ"], bani: "Chaupai Sahib" },
  { prefix: "ਆਦ ", answer: "ਪੁਰਖ", suffix: " ਅਦ੍ਵੈ ਅਬਿਕਾਰਾ॥੩॥", distractors: ["ਅਬਗਤ", "ਲਾਲ", "ਕੁਦਰਤਿ"], bani: "Chaupai Sahib" },
  { prefix: "ਸੱਤ੍ਰ ", answer: "ਮਿੱਤ੍ਰ", suffix: " ਜਿਹ ਤਾਤ ਨਾ ਮਾਤਾ॥", distractors: ["ਰਹਿਆ", "ਕੁੰਡਲ", "ਸਾਜਿ"], bani: "Chaupai Sahib" },
  { prefix: "ਸਭ ਤੇ ", answer: "ਦੂਰਿ", suffix: " ਸਭਨ ਤੇ ਨੇਰਾ॥", distractors: ["ਪੂਰੇ", "ਸਹਸ", "ਜਾਨਾ"], bani: "Chaupai Sahib" },
  { prefix: "ਜਲ ਥਲ ਮਹੀਅਲ ", answer: "ਜਾਹਿ", suffix: " ਬਸੇਰਾ॥੪॥", distractors: ["ਕੰਚਨੁ", "ਰਾਵ", "ਰੁਤਿ"], bani: "Chaupai Sahib" },
  { prefix: "ਅਨਾਜੁ ", answer: "ਮਗਉ", suffix: "; ਸਤ ਸੀਕਾ॥੧॥", distractors: ["ਗਨੀ", "ਦਾਤੇ", "ਕਹਤ"], bani: "Aarti" },
  { prefix: "ਇਕ ", answer: "ਤਾਜਨਿ", suffix: " ਤੁਰੀ ਚੰਗੇਰੀ॥", distractors: ["ਤਰਾ", "ਮਹਿ", "ਵਡਾਈ"], bani: "Aarti" },
  { prefix: "ਊਤਮੁ ਦੀਅਰਾ; ", answer: "ਨਿਰਮਲ", suffix: " ਬਾਤੀ॥", distractors: ["ਨਠੇ", "ਸਤਿਗੁਰਿ", "ਗਿਰੀਵਾਨ"], bani: "Aarti" },
  { prefix: "ਗਊ ", answer: "ਭੈਸ", suffix: " ਮਗਉ ਲਾਵੇਰੀ॥", distractors: ["ਵਾਜੇ", "ਸੰਗਤਿ", "ਸਮਾਲੇ"], bani: "Aarti" },
  { prefix: "ਗੁਰ ", answer: "ਸਾਖੀ", suffix: "; ਜੋਤਿ ਪਰਗਟੁ ਹੋਇ॥", distractors: ["ਕਰਾ", "ਸਵਾਰਣਾ", "ਸੰਗੀ"], bani: "Aarti" },
  { prefix: "ਗੋਪਾਲ ", answer: "ਤੇਰਾ", suffix: " ਆਰਤਾ॥", distractors: ["ਸਭੁ", "ਰਾਜ", "ਹੋਵੈ"], bani: "Aarti" },
  { prefix: "ਘਰ ਕੀ ", answer: "ਗੀਹਨਿ", suffix: " ਚੰਗੀ॥", distractors: ["ਸੁਹਾਵਾ", "ਭੰਜਨੁ", "ਸੁਖ"], bani: "Aarti" },
  { prefix: "ਜਨੁ ", answer: "ਧੰਨਾ", suffix: " ਲੇਵੈ ਮੰਗੀ॥੨॥੪॥", distractors: ["ਦੁਆਰੇ", "ਮਧਿ", "ਪਵੰਦੀਈ"], bani: "Aarti" },
  { prefix: "ਦਾਲਿ ਸੀਧਾ; ", answer: "ਮਾਗਉ", suffix: " ਘੀਉ॥", distractors: ["ਈਸਰੁ", "ਬ੍ਰਹਮਾ", "ਵਾਉ"], bani: "Aarti" },
  { prefix: "ਧੂਪ ਦੀਪ ", answer: "ਘ੍ਰਿਤ", suffix: " ਸਾਜਿ ਆਰਤੀ॥", distractors: ["ਅਨਭੇਖਾ", "ਹੋਈ", "ਨਿਕੀ"], bani: "Aarti" },
  { prefix: "ਪਨੑੀਆ ", answer: "ਛਾਦਨੁ", suffix: " ਨੀਕਾ॥", distractors: ["ਕਰਤਾ", "ਨੀਚੁ", "ਦੀਆ"], bani: "Aarti" },
  { prefix: "ਪੂਰਨ ", answer: "ਪਰਮਾਨੰਦੁ", suffix: " ਬਖਾਨੈ॥੩॥", distractors: ["ਚੰਗੇਰੀ", "ਭਵਾਈਅਹਿ", "ਜੁਗਤੇ॥੫੩"], bani: "Aarti" },
  { prefix: "ਮੰਗਲਾ ", answer: "ਹਰਿ", suffix: " ਮੰਗਲਾ॥", distractors: ["ਸਬਦ", "ਰਸੁ", "ਮਜਨੁ"], bani: "Aarti" },
  { prefix: "ਰਾਮਾ ਭਗਤਿ ", answer: "ਰਾਮਾਨੰਦੁ", suffix: " ਜਾਨੈ॥", distractors: ["ਭਰਪੂਰਿ", "ਸਿਰਜਣਹਾਰੁ", "ਨਮਸਕਾਰੰ"], bani: "Aarti" },
  { prefix: "ਮਾਟੀ ਕੋ ਪੁਤਰਾ. ", answer: "ਕੈਸੇ", suffix: " ਨਚਤੁ ਹੈ॥", distractors: ["ਜਮੁ", "ਏਹੁ", "ਜੁਗੁ"], bani: "Tva Prasad Svaiye" },
];

export type UcharanItem = {
  tukh: string;
  correct: string;
  wrong: string;
  why: string;
};

export const ucharanBank: UcharanItem[] = [
  { tukh: "ਆਦਿ ਸਚੁ ਜੁਗਾਦਿ ਸਚੁ॥",
    correct: "Aad sach jugaad sach",
    wrong: "Aad such jugaad such",
    why: "ਸਚੁ uses Aunkar but stays short, like sach, not such." },
  { tukh: "ਨਾਨਕ ਨਾਮੁ ਚੜ੍ਹਦੀਕਲਾ॥",
    correct: "Naam chardeekala",
    wrong: "Naam chardikalla",
    why: "Bihari ਦੀ stays long, not short." },
  { tukh: "ਸਤਿਗੁਰ ਪ੍ਰਸਾਦਿ॥",
    correct: "Satgur prasaad",
    wrong: "Satigur prasad",
    why: "ਸਤਿ keeps the Sihari subtle; do not stretch it to si." },
  { tukh: "ਵਾਹਿਗੁਰੂ ਜੀ ਕਾ ਖਾਲਸਾ॥",
    correct: "Vaheguru ji ka Khalsa",
    wrong: "Vaaheguru ji ka Khaalsa",
    why: "Both vowels stay short; do not lengthen the kanna." },
  { tukh: "ਜਪੁ ਜਾਪਿ ਜਪਨਹਾਰੁ॥",
    correct: "Jap jaap japanhaar",
    wrong: "Jaap japp japanhar",
    why: "ਜਪੁ keeps the Aunkar subtle, not a long jaap." },
  { tukh: "ਹਰਿ ਕਾ ਨਾਮੁ; ਜਨ ਕਉ ਮੁਕਤਿ ਜੁਗਤਿ॥",
    correct: "Har ka naam jan kau mukat jugat",
    wrong: "Hari ka naam jan kau mukati jugati",
    why: "ਹਰਿ and other Sihari endings should not be over-pronounced." },
  { tukh: "ਕਰਤਾ ਪੁਰਖੁ ਨਿਰਭਉ ਨਿਰਵੈਰੁ॥",
    correct: "Karta purakh nirbhau nirvair",
    wrong: "Kartaa purakh nirbhaau nirvair",
    why: "Final kanna stays subtle, not lengthened." },
];

export type MemoryPair = { word: string; meaning: string };

export const memoryPairs: MemoryPair[] = [
  { word: "ਨਾਮ", meaning: "Name" },
  { word: "ਗੁਰੁ", meaning: "Guru" },
  { word: "ਸਾਚਾ", meaning: "True" },
  { word: "ਮਨ", meaning: "Mind" },
  { word: "ਜੋਤਿ", meaning: "Light" },
  { word: "ਪ੍ਰਭੁ", meaning: "Lord" },
  { word: "ਚਰਨ", meaning: "Feet" },
  { word: "ਕਿਰਪਾ", meaning: "Mercy" },
  { word: "ਦਾਸ", meaning: "Slave" },
  { word: "ਹਉਮੈ", meaning: "Ego" },
  { word: "ਬਾਣੀ", meaning: "Bani" },
  { word: "ਗਿਆਨ", meaning: "Wisdom" },
  { word: "ਅੰਮ੍ਰਿਤ", meaning: "Nectar" },
  { word: "ਅਕਾਲ", meaning: "Timeless" },
  { word: "ਖਾਲਸਾ", meaning: "Pure" },
  { word: "ਨਾਨਕ", meaning: "Nanak" },
  { word: "ਆਨੰਦ", meaning: "Bliss" },
  { word: "ਸੇਵਾ", meaning: "Service" },
  { word: "ਸਿਮਰਨ", meaning: "Remembrance" },
  { word: "ਮਾਤਾ", meaning: "Mother" },
  { word: "ਪਿਤਾ", meaning: "Father" },
  { word: "ਹਰਿ", meaning: "Lord" },
  { word: "ਸਬਦ", meaning: "Word" },
  { word: "ਸੁਖ", meaning: "Comfort" },
  { word: "ਦੁਖ", meaning: "Sorrow" },
  { word: "ਮੁਕਤਿ", meaning: "Liberation" },
  { word: "ਕਾਮ", meaning: "Lust" },
  { word: "ਕ੍ਰੋਧ", meaning: "Anger" },
  { word: "ਲੋਭ", meaning: "Greed" },
  { word: "ਮੋਹ", meaning: "Attachment" },
  { word: "ਜਗਤ", meaning: "World" },
  { word: "ਜਪੁ", meaning: "Meditate" },
  { word: "ਦਇਆ", meaning: "Compassion" },
  { word: "ਧੀਰਜ", meaning: "Patience" },
  { word: "ਪਾਣੀ", meaning: "Water" },
  { word: "ਚੰਦ", meaning: "Moon" },
  { word: "ਸੂਰਜ", meaning: "Sun" },
  { word: "ਹੁਕਮੁ", meaning: "Command" },
  { word: "ਗੁਰਮੁਖਿ", meaning: "Guru-oriented" },
  { word: "ਵਾਹਿਗੁਰੂ", meaning: "Waheguru" },
];

// ---- Gurbani Scrabble (Build the Word) vocab. 115 words filtered to avoid
// halant/conjunct combinations so each codepoint maps cleanly to a tile.
export type ScrabblePair = { word: string; meaning: string };
export const scrabbleBank: ScrabblePair[] = [
  { word: "ਨਾਮ", meaning: "Name" },
  { word: "ਗੁਰੁ", meaning: "Guru" },
  { word: "ਸਾਚਾ", meaning: "True" },
  { word: "ਮਨ", meaning: "Mind" },
  { word: "ਜੋਤਿ", meaning: "Light" },
  { word: "ਚਰਨ", meaning: "Feet" },
  { word: "ਕਿਰਪਾ", meaning: "Mercy" },
  { word: "ਦਾਸ", meaning: "Slave" },
  { word: "ਹਉਮੈ", meaning: "Ego" },
  { word: "ਬਾਣੀ", meaning: "Bani" },
  { word: "ਗਿਆਨ", meaning: "Wisdom" },
  { word: "ਸਤਿ", meaning: "Truth" },
  { word: "ਸਾਚ", meaning: "True" },
  { word: "ਗੁਣ", meaning: "Virtue" },
  { word: "ਜਨ", meaning: "Servant" },
  { word: "ਹਰਿ", meaning: "Lord" },
  { word: "ਨਾਨਕ", meaning: "Nanak" },
  { word: "ਪਿਤਾ", meaning: "Father" },
  { word: "ਮਾਤਾ", meaning: "Mother" },
  { word: "ਰਾਮ", meaning: "Lord" },
  { word: "ਰੰਗ", meaning: "Colour" },
  { word: "ਜੀਉ", meaning: "Life" },
  { word: "ਅਮਰ", meaning: "Eternal" },
  { word: "ਅਕਾਲ", meaning: "Timeless" },
  { word: "ਆਨੰਦ", meaning: "Bliss" },
  { word: "ਚਾਉ", meaning: "Joy" },
  { word: "ਪ੍ਰੇਮ", meaning: "Love" },
  { word: "ਭਗਤ", meaning: "Devotee" },
  { word: "ਸੰਤ", meaning: "Saint" },
  { word: "ਸਾਧ", meaning: "Saint" },
  { word: "ਕਰਤਾ", meaning: "Creator" },
  { word: "ਕਾਲ", meaning: "Time" },
  { word: "ਖਾਲਸਾ", meaning: "Pure" },
  { word: "ਘਰ", meaning: "Home" },
  { word: "ਘਰੁ", meaning: "Home" },
  { word: "ਮਨੁ", meaning: "Mind" },
  { word: "ਸਬਦ", meaning: "Word" },
  { word: "ਸਬਦੁ", meaning: "Word" },
  { word: "ਅੰਮ੍ਰਿਤ", meaning: "Nectar" },
  { word: "ਸੁਖ", meaning: "Comfort" },
  { word: "ਦੁਖ", meaning: "Sorrow" },
  { word: "ਮੁਕਤਿ", meaning: "Liberation" },
  { word: "ਜੁਗ", meaning: "Age" },
  { word: "ਸਚੁ", meaning: "Truth" },
  { word: "ਸਚਾ", meaning: "True" },
  { word: "ਅੰਤ", meaning: "End" },
  { word: "ਆਦਿ", meaning: "Beginning" },
  { word: "ਜਪੁ", meaning: "Meditate" },
  { word: "ਜਪਿ", meaning: "Chant" },
  { word: "ਸੇਵ", meaning: "Service" },
  { word: "ਸਿਮਰਨ", meaning: "Remembrance" },
  { word: "ਮੁਖ", meaning: "Face" },
  { word: "ਨੈਨ", meaning: "Eyes" },
  { word: "ਜਲ", meaning: "Water" },
  { word: "ਥਲ", meaning: "Land" },
  { word: "ਪਉਣ", meaning: "Air" },
  { word: "ਪਾਣੀ", meaning: "Water" },
  { word: "ਅਗਨਿ", meaning: "Fire" },
  { word: "ਧਰਤਿ", meaning: "Earth" },
  { word: "ਅਕਾਸ", meaning: "Sky" },
  { word: "ਚੰਦ", meaning: "Moon" },
  { word: "ਸੂਰਜ", meaning: "Sun" },
  { word: "ਨੀਰ", meaning: "Water" },
  { word: "ਬੀਰ", meaning: "Warrior" },
  { word: "ਧੀਰਜ", meaning: "Patience" },
  { word: "ਮਨੁਖ", meaning: "Human" },
  { word: "ਜਗਤ", meaning: "World" },
  { word: "ਲੋਕ", meaning: "World" },
  { word: "ਪਾਪ", meaning: "Sin" },
  { word: "ਪੁੰਨ", meaning: "Virtue" },
  { word: "ਅਨੰਦ", meaning: "Joy" },
  { word: "ਕਮਲ", meaning: "Lotus" },
  { word: "ਫਲ", meaning: "Fruit" },
  { word: "ਫੁਲ", meaning: "Flower" },
  { word: "ਰਾਜ", meaning: "Kingdom" },
  { word: "ਰੰਕ", meaning: "Pauper" },
  { word: "ਦਾਨ", meaning: "Charity" },
  { word: "ਦਇਆ", meaning: "Compassion" },
  { word: "ਸੀਤ", meaning: "Cold" },
  { word: "ਉਸਣ", meaning: "Heat" },
  { word: "ਮਾਇਆ", meaning: "Illusion" },
  { word: "ਮਾਇ", meaning: "Mother" },
  { word: "ਪੁਤੁ", meaning: "Son" },
  { word: "ਧੀ", meaning: "Daughter" },
  { word: "ਭਰਾਉ", meaning: "Brother" },
  { word: "ਸਖੀ", meaning: "Friend" },
  { word: "ਮਿਤੁ", meaning: "Friend" },
  { word: "ਘਨ", meaning: "Cloud" },
  { word: "ਬੂੰਦ", meaning: "Drop" },
  { word: "ਮੋਤੀ", meaning: "Pearl" },
  { word: "ਹੀਰਾ", meaning: "Diamond" },
  { word: "ਸੋਨਾ", meaning: "Gold" },
  { word: "ਕਾਮ", meaning: "Lust" },
  { word: "ਕ੍ਰੋਧ", meaning: "Anger" },
  { word: "ਲੋਭ", meaning: "Greed" },
  { word: "ਮੋਹ", meaning: "Attachment" },
  { word: "ਅਹੰਕਾਰ", meaning: "Ego" },
  { word: "ਨਿਰਭਉ", meaning: "Fearless" },
  { word: "ਨਿਰਵੈਰੁ", meaning: "Without enmity" },
  { word: "ਅਜੂਨੀ", meaning: "Unborn" },
  { word: "ਸੈਭੰ", meaning: "Self-existent" },
  { word: "ਜੁਗਾਦਿ", meaning: "From beginning" },
  { word: "ਅਨਾਦਿ", meaning: "Beginningless" },
  { word: "ਅਨੰਤ", meaning: "Infinite" },
  { word: "ਏਕ", meaning: "One" },
  { word: "ਏਕੋ", meaning: "One" },
  { word: "ਆਪੁ", meaning: "Self" },
  { word: "ਆਤਮ", meaning: "Soul" },
  { word: "ਪਰਮਾਤਮ", meaning: "Supreme Soul" },
  { word: "ਨਿਰੰਕਾਰ", meaning: "Formless" },
  { word: "ਸਾਹਿਬੁ", meaning: "Master" },
  { word: "ਪ੍ਰਭੁ", meaning: "Lord" },
  { word: "ਖਸਮੁ", meaning: "Master" },
  { word: "ਠਾਕੁਰ", meaning: "Lord" },
  { word: "ਸੁਆਮੀ", meaning: "Lord" },
];
